# Only reached with SONNHEIDE_BUILD_NATIVE=ON. Sources are SHA-256 checked by vendor_native.py.
if(NOT APPLE AND NOT WIN32)
 message(FATAL_ERROR "The native client supports Windows Direct3D11 and macOS Metal; the headless core remains portable.")
endif()
enable_language(C)
if(APPLE)
 enable_language(OBJCXX)
endif()
set(SONNHEIDE_NATIVE_SOURCES "${CMAKE_SOURCE_DIR}/.build/native-sources" CACHE PATH "Pinned native dependency sources")
foreach(dep sdl bgfx-cmake bgfx bx bimg freetype rmlui)
 if(NOT EXISTS "${SONNHEIDE_NATIVE_SOURCES}/${dep}/CMakeLists.txt" AND NOT EXISTS "${SONNHEIDE_NATIVE_SOURCES}/${dep}/include")
  message(FATAL_ERROR "Missing ${dep}; first run python3 tools/vendor_native.py")
 endif()
endforeach()
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Static dependencies" FORCE)
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
set(SDL_TESTS OFF CACHE BOOL "" FORCE)
add_subdirectory("${SONNHEIDE_NATIVE_SOURCES}/sdl" "${CMAKE_BINARY_DIR}/deps/sdl" EXCLUDE_FROM_ALL)
set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
add_subdirectory("${SONNHEIDE_NATIVE_SOURCES}/freetype" "${CMAKE_BINARY_DIR}/deps/freetype" EXCLUDE_FROM_ALL)
# RmlUi's legacy FindFreetype accepts the pinned CMake target and exact headers.
set(FREETYPE_LIBRARY freetype CACHE STRING "Pinned FreeType target" FORCE)
set(FREETYPE_INCLUDE_DIR_freetype2 "${SONNHEIDE_NATIVE_SOURCES}/freetype/include" CACHE PATH "" FORCE)
set(FREETYPE_INCLUDE_DIR_ft2build "${SONNHEIDE_NATIVE_SOURCES}/freetype/include" CACHE PATH "" FORCE)
set(BUILD_UNIVERSAL_BINARIES OFF CACHE BOOL "" FORCE)
set(BUILD_SAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_PRECOMPILED_HEADERS OFF CACHE BOOL "" FORCE)
set(SONNHEIDE_PREV_BUILD_TESTING ${BUILD_TESTING})
set(BUILD_TESTING OFF)
add_subdirectory("${SONNHEIDE_NATIVE_SOURCES}/rmlui" "${CMAKE_BINARY_DIR}/deps/rmlui" EXCLUDE_FROM_ALL)
set(BUILD_TESTING ${SONNHEIDE_PREV_BUILD_TESTING})
set(BX_DIR "${SONNHEIDE_NATIVE_SOURCES}/bx" CACHE PATH "" FORCE)
set(BIMG_DIR "${SONNHEIDE_NATIVE_SOURCES}/bimg" CACHE PATH "" FORCE)
set(BGFX_DIR "${SONNHEIDE_NATIVE_SOURCES}/bgfx" CACHE PATH "" FORCE)
set(BGFX_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BGFX_BUILD_EXAMPLE_COMMON OFF CACHE BOOL "" FORCE)
set(BGFX_INSTALL OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_VIDEO OFF CACHE BOOL "" FORCE)
set(BGFX_CONFIG_RENDERER_WEBGPU OFF CACHE BOOL "" FORCE)
add_subdirectory("${SONNHEIDE_NATIVE_SOURCES}/bgfx-cmake" "${CMAKE_BINARY_DIR}/deps/bgfx" EXCLUDE_FROM_ALL)

# The menu only consumes original JPEG and PNG. Keep bimg's pinned parser while
# avoiding unused AVIF/EXR/SVG codecs and their runtime dependencies.
get_target_property(SONNHEIDE_BIMG_DECODE_SOURCES bimg_decode SOURCES)
list(FILTER SONNHEIDE_BIMG_DECODE_SOURCES EXCLUDE REGEX "/(dav1d|libavif)/")
set_property(TARGET bimg_decode PROPERTY SOURCES "${SONNHEIDE_BIMG_DECODE_SOURCES}")
target_compile_definitions(bimg_decode PRIVATE BIMG_CONFIG_PARSE_ENABLE=0 BIMG_CONFIG_PARSE_JPEG=1 BIMG_CONFIG_PARSE_PNG=1 BIMG_CONFIG_USE_STB_IMAGE=1 BIMG_CONFIG_USE_WIC=0)
