#include "sonnheide/earth_world.hpp"
#include <algorithm>
#include <cmath>
#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace sonnheide::earth;
namespace {
void check(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
template<class F>void rejects(F f,const char* reason){bool failed=false;try{f();}catch(const std::exception&){failed=true;}check(failed,reason);}
bool close(double a,double b,double tolerance=1e-5){return std::abs(a-b)<tolerance;}
}
int main(int argc,char**argv){
 int passed=0;auto test=[&](const char*name,const std::function<void()>&run){try{run();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception&e){std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';std::exit(1);}};
 test("AEQD both axes use metres and date line is local",[]{Projection p({179.9,10});auto q=p.forward({-179.9,10});check(std::hypot(q.x,q.y)<22000,"Date line became a world-sized seam");auto r=p.inverse(q);check(close(r.longitude,-179.9)&&close(r.latitude,10),"Date line roundtrip mismatch");auto east=Projection({0,0}).forward({1,0}),north=Projection({0,0}).forward({0,1});check(close(std::hypot(east.x,east.y),std::hypot(north.x,north.y)),"Axes have different scales");});
 test("AEQD polar forward inverse and singularity admission",[]{for(auto origin:std::vector<LonLat>{{0,90},{0,-90},{30,89.9},{-179,0}}){Projection p(origin);for(auto point:std::vector<Point>{{0,0},{1000,2000},{-50000,75000}}){auto r=p.forward(p.inverse(point));check(std::hypot(r.x-point.x,r.y-point.y)<.002,"Polar inverse drift");}}rejects([]{Projection({0,0}).forward({180,0});},"Antipodal singularity accepted");rejects([]{Projection({0,0}).inverse({21000000,0});},"Inverse outside disk accepted");rejects([]{Projection({0,91});},"Impossible geographic origin accepted");rejects([]{Projection({0,0}).forward({0,std::numeric_limits<double>::quiet_NaN()});},"Nonfinite query accepted");});
 auto directory=argc>1?std::filesystem::path(argv[1]):std::filesystem::path(".build/geography-sources");
 if(!std::filesystem::exists(directory/"gshhs_f.b")){std::cerr<<"Complete geography sources missing; run python3 tools/prepare_geography.py --fetch\n";return 2;}
 std::shared_ptr<GeoAtlas> atlas;
 test("All five actual original source SHA256s admitted",[&]{atlas=GeoAtlas::load(directory);check(atlas->source_hash()=="28600e8f7a08645aab43079326df6504212ec5ccb2b4bcf3b5f4f12ed60e82bc","Source identity is not complete ZIP");check(atlas->rings(Detail::Full).size()>180000&&atlas->rings(Detail::Coarse).size()>1700,"Global full/LOD sources incomplete");});
 test("Actual continental land oceans lakes island and Antarctic convention",[&]{check(atlas->land({8.55,47.37}),"Zurich not land");check(!atlas->land({0,0}),"Gulf of Guinea not water");check(!atlas->land({9.4,47.62}),"Lake Constance not water");check(atlas->land({7.889,54.182}),"Heligoland small island lost");check(atlas->land({0,-89}),"Antarctic polar cap lost");check(!atlas->land({0,89}),"North Pole became land");for(const auto&r:atlas->rings(Detail::Full))check(r.level!=6,"Grounding line double-counted");});
 test("Antarctic island polygons are not turned into spurious polar caps",[&]{int caps=0;for(const auto&ring:atlas->rings(Detail::Coarse)){bool has_pole=false;for(auto v:ring.vertices)if(v.latitude<=-89.999)has_pole=true;if(has_pole){++caps;check(ring.west<=-179.999&&ring.east>=179.999&&ring.south<=-89.999,"Local Antarctic island acquired world-spanning pole vertices");}}check(caps==1,"Ice-front convention must have exactly one polar mainland cap");check(!atlas->land({-58.7,-64.5}),"Small Antarctic island generated false land toward the pole");});
 WorldConfig config;config.centre={14.382,40.626};config.world_scale=.04;config.grid_cells_x=64;config.grid_cells_y=64;std::shared_ptr<const EarthWorldDefinition> coast;
 test("Real selected coast contains both land and sea with finite authoritative domain",[&]{coast=EarthWorldDefinition::create(atlas,config);std::size_t lands=0,waters=0;for(auto c:coast->cells())(c.land?lands:waters)++;check(lands>100&&waters>100,"Real Amalfi coast became a synthetic all-land/water map");check(coast->sample({0,0}).land,"Amalfi centre should be land");check(!coast->sample({-1000,-1000}).land,"Selected real offshore became land");check(!coast->sample({100000,0}).authoritative&&!coast->sample({100000,0}).land,"Presentation sea allocated world cells");});
 test("Core full geometry agrees independently with global full-source queries",[&]{for(int y=-5;y<=5;++y)for(int x=-5;x<=5;++x){Point p{x*280.,y*280.};check(coast->sample(p).source_land==atlas->land(coast->geographic(p)),"Clipped local full geometry changed original core shore");}});
 test("Cell budget and navigation LOD cannot change canonical highest-preview geometry",[&]{auto c=config;c.grid_cells_x=8;c.grid_cells_y=8;auto coarse=EarthWorldDefinition::create(atlas,c);for(int y=-10;y<=10;++y)for(int x=-10;x<=10;++x){Point p{x*191.37,y*183.93};auto a=coast->sample(p),b=coarse->sample(p);check(a.land==b.land&&a.source_land==b.source_land&&a.water_region==b.water_region&&close(a.height_m,b.height_m),"Grid resolution changed game/preview coastline");}check(coarse->recipe_hash()!=coast->recipe_hash(),"Candidate descriptor omitted cell budget");});
 test("Frozen bounded shore slope and absolutely flat inland",[&]{bool found_slope=false;for(int y=-100;y<=100;++y)for(int x=-100;x<=100;++x){auto s=coast->sample({x*17.31,y*18.27});check(s.height_m<=config.land_height_m&&s.height_m>=-config.water_depth_m,"Height outside fixed profile");if(s.land){check(s.height_m>=0,"Land submerged");if(s.coast_distance_m>=config.coast_width_m)check(close(s.height_m,config.land_height_m),"Inland not exactly level");if(s.height_m>0&&s.height_m<config.land_height_m)found_slope=true;}else check(s.height_m<=0,"Water became support");}check(found_slope,"Actual natural coast has no gradual shore band");});
 test("All-inland selections gain irregular closure only inside narrow band",[&]{auto c=config;c.centre={8.55,47.37};c.world_scale=1;c.grid_cells_x=32;c.grid_cells_y=32;auto inland=EarthWorldDefinition::create(atlas,c);auto selection=inland->selection_bounds(),domain=inland->domain_bounds();for(int y=-6;y<=6;++y)for(int x=-6;x<=6;++x){Point p{x*250.,y*250.};check(inland->sample(p).land==atlas->land(inland->geographic(p)),"Closure changed interior true geography");}int varying=0;bool last=false;for(int y=-1900;y<=1900;y+=10){bool on=inland->sample({selection.min_x+45.,double(y)}).land;if(y>-1900&&on!=last)++varying;last=on;}check(varying>3,"Closure is a straight rectangular cut");check(!inland->sample({selection.min_x,0}).land,"Selection edge has no sea closure");check(inland->sample({domain.min_x+1,0}).guard,"Outer protection strip missing");check(!inland->sample({domain.min_x+1,0}).land,"Sea guard is fillable land");check(inland->water_region_count()>=1,"Pure sea collar has no connected water");});
 test("Final topology distinguishes uncut lake and reopened lake",[&]{WorldConfig c=config;c.centre={9.4,47.62};c.world_scale=.06;c.grid_cells_x=128;c.grid_cells_y=128;auto lake=EarthWorldDefinition::create(atlas,c);check(!lake->sample({0,0}).land,"Lake source lost");check(lake->water_region_count()>=2&&lake->sample({0,0}).water_region>1,"Interior lake assigned same region as exterior sea");c.width_m=1024;c.height_m=1024;c.closure_band_m=80;c.coast_width_m=24;c.world_scale=.08;c.grid_cells_x=64;c.grid_cells_y=64;auto cut=EarthWorldDefinition::create(atlas,c);check(!cut->sample({0,0}).land&&cut->water_region_count()==1&&cut->sample({0,0}).water_region==1,"Cut lake retained obsolete isolated source lake identity");});
 test("Small island survives even at coarse bookkeeping grid",[&]{auto c=config;c.centre={7.889,54.182};c.world_scale=.15;c.width_m=4096;c.height_m=4096;c.grid_cells_x=8;c.grid_cells_y=8;auto island=EarthWorldDefinition::create(atlas,c);check(island->sample({0,0}).land,"Full island replaced by coarse cell centre mask");check(!island->sample({1000,1000}).land,"Island surrounding sea became land");});
 test("Real full-source polar and date-line selections have no longitude seam",[&]{auto c=config;c.centre={179.9,-16.5};c.grid_cells_x=16;c.grid_cells_y=16;auto date=EarthWorldDefinition::create(atlas,c);for(auto p:std::vector<Point>{{0,0},{1000,0},{-1000,0},{0,1000}})check(date->sample(p).source_land==atlas->land(date->geographic(p)),"Dateline closure used far-side geography");c.centre={0,-90};auto south=EarthWorldDefinition::create(atlas,c);check(south->sample({0,0}).land,"Antarctic selected polar interior lost");c.centre={0,90};auto north=EarthWorldDefinition::create(atlas,c);check(!north->sample({0,0}).land,"North Polar sea became land");});
 test("Seed is frozen, creation repeatable, profile changes invalidate recipe",[&]{auto same=EarthWorldDefinition::create(atlas,config);check(same->recipe_hash()==coast->recipe_hash(),"Same final candidate produced different recipe");auto c=config;c.seed++;auto other=EarthWorldDefinition::create(atlas,c);check(other->recipe_hash()!=coast->recipe_hash(),"Seed omitted from frozen descriptor");auto before=coast->sample({1700,-1700});for(int i=0;i<100;++i)coast->sample({i*3.,i*7.});auto after=coast->sample({1700,-1700});check(before.land==after.land&&before.height_m==after.height_m,"Camera queries mutate geographic state");});
 test("Cancellation admission and impossible source/projection budget reject",[&]{rejects([&]{EarthWorldDefinition::create(atlas,config,[]{return true;});},"Cancelled creation completed");auto c=config;c.closure_band_m=3000;rejects([&]{EarthWorldDefinition::create(atlas,c);},"Closure erasing interior accepted");c=config;c.width_m=10000000;rejects([&]{EarthWorldDefinition::create(atlas,c);},"Projection budget accepted unbounded map");});
 test("Actual source byte corruption rejected before candidate creation",[&]{auto tmp=std::filesystem::temp_directory_path()/("sonnheide-geography-sha-negative-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));std::filesystem::create_directories(tmp);std::filesystem::copy_file(directory/"gshhs_f.b",tmp/"gshhs_f.b",std::filesystem::copy_options::overwrite_existing);{std::fstream f(tmp/"gshhs_f.b",std::ios::binary|std::ios::in|std::ios::out);f.seekp(60);f.put(0x7f);}rejects([&]{GeoAtlas::load(tmp);},"Forged source geometry admitted");std::filesystem::remove_all(tmp);});
 std::cout<<passed<<" geography production tests passed\n";
}
