#include "sonnheide/simulation.hpp"
#include <functional>
#include <iostream>
#include <limits>
#include <random>
#include <sstream>
#include <stdexcept>

namespace {
using namespace sonnheide;
void check(bool ok,const std::string& why){if(!ok) throw std::runtime_error(why);}
Simulation coast(Quantity materials=100){std::vector<Surface> cells(36,Surface::Water);for(int z=0;z<6;++z) cells[static_cast<std::size_t>(z)*6]=Surface::Land;return Simulation(FrozenWorld(6,6,std::move(cells)),{{7,{materials,0}},{8,{20,0}}});}
Result issue(Simulation& s,const std::string& id,Payload payload,Principal who=Principal::Player,EntityId actor=7){return s.submit({id,s.revision(),std::move(payload)},{who,actor});}
void accepted(Result r){check(r.status==Status::Accepted,"expected Accepted, got "+r.reason);}
EntityId reclaim(Simulation& s,const std::string& prefix,Cell cell){auto r=issue(s,prefix+"p",PlanReclamation{cell,7});accepted(r);accepted(issue(s,prefix+"w",ContributeWork{r.created,5},Principal::Scheduler));return r.created;}
template<class F> void throws(F f){bool caught=false;try{f();}catch(const std::exception&){caught=true;}check(caught,"expected rejection of checkpoint");}
}
int main(){
  int passed=0;
  auto test=[&](const char* name,const std::function<void()>& f){try{f();++passed;std::cout<<"PASS "<<name<<'\n';}catch(const std::exception& e){std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';throw;}};
  try {
    test("completed-only land and material consumption",[]{auto s=coast();auto hash=s.world().natural_fingerprint();auto r=issue(s,"plan",PlanReclamation{{1,2},7});accepted(r);check(s.world().effective({1,2})==Surface::Water,"reserved site became land");check(s.stock().at(7)==Stock{90,10},"reservation incorrect");accepted(issue(s,"work1",ContributeWork{r.created,2},Principal::Scheduler));check(s.world().effective({1,2})==Surface::Water,"partial site became land");accepted(issue(s,"work2",ContributeWork{r.created,3},Principal::Scheduler));check(s.world().effective({1,2})==Surface::Land && s.stock().at(7)==Stock{90,0},"completion incorrect");check(hash==s.world().natural_fingerprint(),"natural map mutated");});
    test("four-neighbor support, planned cells cannot support new land",[]{auto s=coast();check(issue(s,"island",PlanReclamation{{3,3},7}).reason=="NO_LAND_ADJACENCY","island admitted");accepted(issue(s,"edge",PlanReclamation{{1,2},7}));check(issue(s,"future",PlanReclamation{{2,2},7}).reason=="NO_LAND_ADJACENCY","reserved support admitted");reclaim(s,"other",{1,3});check(issue(s,"diagonal",PlanReclamation{{2,4},7}).reason=="NO_LAND_ADJACENCY","diagonal support admitted");});
    test("rejected transaction does not leak materials, jobs, history",[]{auto s=coast(9);auto rev=s.revision();check(issue(s,"poor",PlanReclamation{{1,1},7}).reason=="INSUFFICIENT_MATERIAL","unexpected failure");check(s.revision()==rev && s.jobs().empty() && s.events().empty() && s.stock().at(7)==Stock{9,0},"rejection mutated primary world");});
    test("same command retries once; changed payload conflicts",[]{auto s=coast();Command c{"same",0,PlanReclamation{{1,1},7}};auto first=s.submit(c,{Principal::Player,7});accepted(first);check(s.submit(c,{Principal::Player,7})==first,"retry changed result");check(s.stock().at(7)==Stock{90,10} && s.jobs().size()==1,"double reservation");c.payload=PlanReclamation{{1,2},7};check(s.submit(c,{Principal::Player,7}).reason=="COMMAND_ID_CONFLICT","changed payload reused id");check(s.submit({"same",0,PlanReclamation{{1,1},7}},{Principal::Observer,7}).reason=="COMMAND_ID_CONFLICT","receipt leaked across authority");});
    test("stale preview is rejected and needs a fresh command id",[]{auto s=coast();accepted(issue(s,"first",PlaceRoad{{0,1}}));auto r=s.submit({"stale",0,PlanReclamation{{1,2},7}},{Principal::Player,7});check(r.status==Status::RequiresRepreview && s.jobs().empty(),"stale preview committed");check(s.submit({"stale",s.revision(),PlanReclamation{{1,2},7}},{Principal::Player,7}).reason=="COMMAND_ID_CONFLICT","revision change reused command id");accepted(issue(s,"fresh",PlanReclamation{{1,2},7}));});
    test("authority cannot be supplied through payload; foreign stock protected",[]{auto s=coast();check(issue(s,"observe",PlanReclamation{{1,2},7},Principal::Observer).reason=="AUTHORITY_DENIED","observer mutation");check(issue(s,"steal",PlanReclamation{{1,2},8}).reason=="NOT_OWNER","foreign material used");auto job=issue(s,"plan",PlanReclamation{{1,2},7});accepted(job);check(issue(s,"fake-work",ContributeWork{job.created,5}).reason=="AUTHORITY_DENIED","player created labor");check(s.stock().at(8)==Stock{20,0},"other owner changed");});
    test("cancel returns staged materials and completed land is permanent",[]{auto s=coast();auto job=issue(s,"plan",PlanReclamation{{1,1},7});accepted(job);accepted(issue(s,"partial",ContributeWork{job.created,1},Principal::Scheduler));accepted(issue(s,"cancel",CancelReclamation{job.created}));check(s.stock().at(7)==Stock{100,0} && !s.world().construction({1,1}),"cancel leak");auto done=reclaim(s,"done",{1,1});check(issue(s,"undo",CancelReclamation{done}).reason=="JOB_TERMINAL","completed land undone");});
    test("construction changes invalidate water graph immediately",[]{auto s=coast();s.rebuild_navigation();check(s.world().water_reachable({1,1},{5,5}),"baseline path absent");auto epoch=s.world().navigation_epoch();auto job=issue(s,"plan",PlanReclamation{{1,1},7});accepted(job);check(!s.world().navigation_ready() && s.world().navigation_epoch()>epoch && !s.world().water_reachable({1,1},{5,5}),"old nav served");accepted(issue(s,"cancel",CancelReclamation{job.created}));s.rebuild_navigation();check(s.world().water_reachable({1,1},{5,5}),"cancel did not restore route");});
    test("single strait deletion splits distant water components",[]{std::vector<Surface> cells(15,Surface::Water);cells[2]=Surface::Land;cells[12]=Surface::Land;Simulation s(FrozenWorld(5,3,cells),{{7,{100,0}}});s.rebuild_navigation();check(s.world().water_reachable({0,1},{4,1}),"strait originally blocked");reclaim(s,"strait",{2,1});s.rebuild_navigation();check(!s.world().water_reachable({0,1},{4,1}),"remote connectivity stayed stale");});
    test("port reclaimed-only, water berth protected, stale nav rejected",[]{auto s=coast();s.rebuild_navigation();check(issue(s,"natural",KernelPlacePort{{0,2},1,2,0,true,s.world().navigation_epoch()}).reason=="CORE_NOT_RECLAIMED","natural port admitted");accepted(issue(s,"road",PlaceRoad{{0,2}}));reclaim(s,"a",{1,2});reclaim(s,"b",{1,3});auto old=s.world().navigation_epoch()-1;s.rebuild_navigation();check(issue(s,"old",KernelPlacePort{{1,2},1,2,0,true,old}).reason=="NAVIGATION_STALE","stale nav admitted");accepted(issue(s,"port",KernelPlacePort{{1,2},1,2,0,true,s.world().navigation_epoch()}));check(issue(s,"block",PlanReclamation{{2,2},7}).reason=="BERTH_PROTECTED","berth reclaimed");check(issue(s,"overlap",KernelPlacePort{{1,2},1,2,0,true,s.world().navigation_epoch()}).reason=="SITE_OCCUPIED","overlap admitted");});
    test("all four rotations rotate core, sea zone and road entry together",[]{for(int rotation:{0,90,180,270}){FrozenWorld probe(10,10,std::vector<Surface>(100,Surface::Land));KernelPlacePort p{{3,3},2,2,rotation,false,0};auto geometry=probe.port_geometry(p);std::vector<Surface> cells(100,Surface::Land);for(auto c:geometry.core) cells[static_cast<std::size_t>(c.z)*10+static_cast<std::size_t>(c.x)]=Surface::Water;for(auto c:geometry.berth) cells[static_cast<std::size_t>(c.z)*10+static_cast<std::size_t>(c.x)]=Surface::Water;Simulation s(FrozenWorld(10,10,cells),{{7,{100,0}}});accepted(issue(s,"road",PlaceRoad{geometry.roadSide.front()}));int i=0;for(auto c:geometry.core) reclaim(s,std::to_string(i++),c);s.rebuild_navigation();p.navigationEpoch=s.world().navigation_epoch();accepted(issue(s,"port",p));s.validate();}});
    test("lake is not an ocean and arbitrary port rotation rejected",[]{auto s=coast();check(issue(s,"diagonal",KernelPlacePort{{1,2},1,2,45,false,0}).reason=="ORTHOGONAL_ROTATION_REQUIRED","diagonal admitted");std::vector<Surface> cells(25,Surface::Land);cells[12]=Surface::Water;FrozenWorld lake(5,5,cells);lake.rebuild_navigation();check(!lake.ocean_reachable({2,2}),"enclosed lake called ocean");});
    test("checkpoint mid-work and receipts roundtrip, continuation identical",[]{auto a=coast();Command c{"plan",0,PlanReclamation{{1,2},7}};auto r=a.submit(c,{Principal::Player,7});accepted(r);accepted(issue(a,"partial",ContributeWork{r.created,2},Principal::Scheduler));std::stringstream out;a.save(out);auto b=Simulation::load(out);check(a.state_fingerprint()==b.state_fingerprint(),"checkpoint state changed");check(b.submit(c,{Principal::Player,7})==r && b.stock().at(7)==Stock{90,10},"retry after load double consumed");auto ra=issue(a,"finish",ContributeWork{r.created,3},Principal::Scheduler),rb=issue(b,"finish",ContributeWork{r.created,3},Principal::Scheduler);check(ra==rb && a.state_fingerprint()==b.state_fingerprint(),"resumed continuation differs");a.rebuild_navigation();std::stringstream ready;a.save(ready);auto d=Simulation::load(ready);check(a.state_fingerprint()==d.state_fingerprint(),"ready nav roundtrip differs");});
    test("incompatible, corrupt and truncated checkpoint rejected",[]{auto s=coast();std::stringstream out;s.save(out);auto bytes=out.str();auto bad=bytes;bad.replace(0,18,"SONNHEIDE_KERNEL 9");std::stringstream a(bad);throws([&]{Simulation::load(a);});auto maskStart=bytes.find('\n',bytes.find('\n')+1)+1;bad=bytes;bad[maskStart]=bad[maskStart]=='0'?'1':'0';std::stringstream b(bad);throws([&]{Simulation::load(b);});std::stringstream c(bytes.substr(0,bytes.size()/2));throws([&]{Simulation::load(c);});std::stringstream d(bytes+"junk");throws([&]{Simulation::load(d);});});
    test("seeded 2000-command stress preserves material and natural map",[]{auto s=coast(10000);auto natural=s.world().natural_fingerprint();std::mt19937 rng(42);for(int i=0;i<2000;++i){int choice=static_cast<int>(rng()%3);auto id=std::to_string(i);if(choice==0) issue(s,id,PlanReclamation{{static_cast<int>(rng()%6),static_cast<int>(rng()%6)},7});else if(!s.jobs().empty()){auto it=s.jobs().begin();std::advance(it,static_cast<long>(rng()%s.jobs().size()));if(choice==1) issue(s,id,ContributeWork{it->first,static_cast<Quantity>(1+rng()%5)},Principal::Scheduler);else issue(s,id,CancelReclamation{it->first});}s.validate();Quantity completed=0;for(auto& [j,job]:s.jobs()){(void)j;if(job.phase==JobPhase::Complete) ++completed;}auto stock=s.stock().at(7);check(stock.available+stock.reserved+completed*10==10000,"material not conserved");check(s.world().natural_fingerprint()==natural,"natural map changed");}});
    test("checkpoint cannot forge unsupported jobs or completed islands",[]{std::vector<Surface> cells(25,Surface::Water);cells[0]=Surface::Land;FrozenWorld map(5,5,cells);for(int phase:{0,2}){std::ostringstream bytes;bytes<<"SONNHEIDE_KERNEL 1\n5 5 "<<map.natural_fingerprint()<<"\n1"<<std::string(24,'0')<<"\n0 2 1 0\n1\n7 90 "<<(phase==0?10:0)<<"\n1\n1 4 4 7 10 "<<(phase==0?0:5)<<' '<<phase<<"\n0\n0\n0\n0\n";std::stringstream input(bytes.str());throws([&]{Simulation::load(input);});}});
    test("public geometry and checkpoint epochs have bounded arithmetic",[]{auto s=coast();check(s.world().port_geometry({{std::numeric_limits<int>::max(),2},2,2,0,false,0}).core.empty(),"overflow anchor accepted");check(!s.world().adjacent_land({std::numeric_limits<int>::max(),0}),"overflow adjacency accepted");std::ostringstream bytes;s.save(bytes);auto text=bytes.str();auto location=text.find("\n0 1 1 0\n");check(location!=std::string::npos,"fixture epoch header absent");text.replace(location,9,"\n0 1 "+std::to_string(std::numeric_limits<std::uint64_t>::max())+" 0\n");std::stringstream input(text);throws([&]{Simulation::load(input);});});
    test("checkpoint cannot forge observer authority or dangling accepted receipts",[]{auto s=coast();accepted(issue(s,"road",PlaceRoad{{0,1}}));std::ostringstream bytes;s.save(bytes);const std::string original="\"road\" \"0:3:0,1\" 0 7 0 \"\" 1 0\n";for(auto replacement:{std::string("\"road\" \"0:3:0,1\" 2 7 0 \"\" 1 0\n"),std::string("\"road\" \"0:3:0,1\" 0 0 0 \"\" 1 0\n"),std::string("\"road\" \"0:3:0,1\" 0 7 0 \"\" 1 999\n")}){auto text=bytes.str();auto location=text.find(original);check(location!=std::string::npos,"receipt fixture missing");text.replace(location,original.size(),replacement);std::stringstream input(text);throws([&]{Simulation::load(input);});}});
    std::cout<<passed<<" kernel scenarios passed\n"; return 0;
  }catch(const std::exception&){return 1;}
}
