#include "../../src/core/sonnheide.hpp"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <fstream>
#include <iostream>
#include <thread>
using namespace sonn;
namespace fs=std::filesystem;
namespace {
unsigned checks=0;
void check(bool x,const char* message){++checks;if(!x)throw std::runtime_error(message);}
template<class F>void reject(F f,std::string_view code={}){++checks;try{f();}catch(const Error&e){if(code.empty()||e.code==code)return;throw std::runtime_error("wrong error "+e.code+" expected "+std::string(code));}throw std::runtime_error("operation accepted invalid input");}
void write(const fs::path&p,std::span<const uint8_t>b){fs::create_directories(p.parent_path());std::ofstream f(p,std::ios::binary);f.write(reinterpret_cast<const char*>(b.data()),std::streamsize(b.size()));if(!f)throw std::runtime_error("fixture write");}
void write(const fs::path&p,std::string_view s){write(p,std::span(reinterpret_cast<const uint8_t*>(s.data()),s.size()));}
DefinitionPackage definitions(const fs::path&root){write(root/"definition.json","{\"height\":2000}");write(root/"texture.bin","S01-original-pixel-fixture");Json dm=Json::Object{{"format","SonnDefinitions1"},{"files",Json::Array{Json::Object{{"path","definition.json"},{"sha256",hex(sha256("{\"height\":2000}"))}}}}};write(root/"definitions.json",canonical_json(dm));Json am=Json::Object{{"format","SonnAssets1"},{"files",Json::Array{Json::Object{{"path","texture.bin"},{"sha256",hex(sha256("S01-original-pixel-fixture"))}}}}};write(root/"assets.json",canonical_json(am));auto d=admit_definitions(root/"definitions.json",root);d.asset_hash=admit_assets(root/"assets.json",root);return d;}
CreationDraft draft(){CreationDraft d;d.core_width=32;d.core_height=32;d.world_id=uuid_from_hex("11111111111111111111111111111111");d.name="圣原 · Sonnheide";for(size_t i=0;i<d.seed.size();i++)d.seed[i]=uint8_t(i);return d;}
void be(Bytes&b,int32_t v){for(int i=3;i>=0;i--)b.push_back(uint8_t(uint32_t(v)>>(i*8)));}
void ring(Bytes&b,int id,int level,int parent,std::vector<std::pair<int32_t,int32_t>>points,bool source_declares_pole=false){int32_t west=INT32_MAX,east=INT32_MIN,south=INT32_MAX,north=INT32_MIN;for(auto[x,y]:points){west=std::min(west,x);east=std::max(east,x);south=std::min(south,y);north=std::max(north,y);}if(source_declares_pole)south=-90000000;for(auto v:{id,int(points.size()),level|(15<<8),west,east,south,north,1,1,parent,-1})be(b,v);for(auto[x,y]:points){be(b,x);be(b,y);}}
Bytes geography_fixture(){Bytes b;ring(b,1,1,-1,{{179000000,-2000000},{181000000,-2000000},{181000000,2000000},{179000000,2000000},{179000000,-2000000}});ring(b,2,2,1,{{179500000,-1000000},{180500000,-1000000},{180500000,1000000},{179500000,1000000},{179500000,-1000000}});ring(b,3,3,2,{{179800000,-500000},{180200000,-500000},{180200000,500000},{179800000,500000},{179800000,-500000}});return b;}
void json_and_hash(){check(hex(sha256("abc"))=="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad","SHA256 abc");check(hex(sha256(""))=="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","SHA256 empty");auto j=parse_json(" {\"de\":\"Ähren\",\"zh\":\"圣原\",\"min\":-9223372036854775808,\"max\":9223372036854775807} ");check(parse_json(canonical_json(j))==j,"int64/Chinese/German roundtrip");reject([]{parse_json("{\"x\":1,\"x\":2}");},"DUPLICATE_KEY");reject([]{parse_json("1.0");},"JSON_FLOAT");reject([]{parse_json("9223372036854775808");},"INTEGER_OVERFLOW");reject([]{parse_json("\"e\\u0301\"");},"NON_NFC");reject([]{parse_json("\"\\ud800\"");},"INVALID_JSON");reject([]{parse_json(std::string("\"\xc0\x80\"",4));},"INVALID_UTF8");reject([]{parse_json("01");});reject([]{parse_json("true false");});std::string nested(66,'[');nested+='0';nested+=std::string(66,']');reject([&]{parse_json(nested);},"JSON_LIMIT");check(canonical_json(parse_json("{\"z\":true,\"a\":\"\\u0001\"}"))=="{\"a\":\"\\u0001\",\"z\":true}","canonical ordering/escaping");}
void rng(){Hash seed{};for(size_t i=0;i<32;i++)seed[i]=uint8_t(i);auto defs=hash_from_hex(std::string(64,'a'));Ref r{uuid_from_hex(std::string(32,'1')),"actor",2,3};auto p=rng_preimage(seed,"birth",r,defs,4,5,0);check(p.size()==138,"SONNRNG1 length");check(hex(sha256(p))=="6e06533805a74a3be070d32ab50aad029c92e89b17a5296a8f6dd0205d861ac9","independent SONNRNG1 byte digest vector");check(std::string(p.begin(),p.begin()+8)=="SONNRNG1"&&p[40]==5&&p[41]==0&&p[78]==3,"SONNRNG1 byte fields");auto a=uniform_rng(seed,"birth",r,defs,4,5,10000),b=uniform_rng(seed,"birth",r,defs,4,5,10000);check(a.value==7070&&a.value==b.value&&a.next_draw_index==6&&a.value<10000,"RNG replay");check(!reduce_uniform_raw(UINT64_MAX,10)&&reduce_uniform_raw(17,10)==7,"rejection removes modulo bias");check(uniform_rng(seed,"birth",r,defs,4,5,1).value==0,"unit RNG bound");reject([&]{uniform_rng(seed,"birth",r,defs,4,5,0);},"RNG_BOUND");reject([&]{uniform_rng(seed,"birth",r,defs,4,UINT64_MAX,10);},"RNG_COUNTER_OVERFLOW");r.kind="bogus";reject([&]{rng_preimage(seed,"birth",r,defs,4,5,0);},"RNG_REF");r.kind="person";reject([&]{rng_preimage(seed,"birth",r,defs,4,5,0);},"RNG_REF");r.kind="permission";reject([&]{rng_preimage(seed,"birth",r,defs,4,5,0);},"RNG_REF");check(canonical_kind("city")=="settlement"&&canonical_kind("animal")=="actor","canonical view aliases");r.kind="actor";check(parse_ref(ref_json(r))==r,"strict Ref roundtrip");auto bad=ref_json(r);std::get<Json::Object>(bad.value)["generation"]=0;reject([&]{parse_ref(bad);},"INVALID_REF");}
void terrain(const DefinitionPackage&defs){auto w=create_candidate(draft(),defs);auto original=w.deterministic_hash();check(w.population==0&&w.buildings==0&&w.awakened_animals==0,"empty initial world");auto unicode_name=draft();unicode_name.name.clear();for(int i=0;i<128;++i)unicode_name.name+="界";check(create_candidate(unicode_name,defs).name==unicode_name.name,"Name contract accepts128 Unicode code points");unicode_name.name+="界";reject([&]{create_candidate(unicode_name,defs);},"INVALID_NAME");check(w.terrain.width==48&&w.terrain.height==48,"guard dimensions");auto support=w.terrain.support(17000,17000);check(support&&support->height_mm==2000&&support->editable&&!support->wet,"support at soil");check(w.terrain.at(0,0).kind==TerrainKind::DeepOcean&&w.terrain.at(8,8).theme==1,"fixed guard/default flower ground");auto top=w.terrain.raycast({17,10,17},{0,-1,0});check(top&&top->position.y==2&&top->normal.y==1,"ray same top");auto side=w.terrain.raycast({15,1,17},{1,0,0},10);check(side&&side->position.x==16&&side->normal.x==-1&&side->kind==TerrainKind::Soil,"ray exposed cliff");auto mesh=w.terrain.mesh(8,8,1,1);check(mesh.indices.size()==18,"top and two exposed sides");check(w.deterministic_hash()==original,"camera/mesh/query cannot change World");check(!w.terrain.support(-1,0)&&!w.terrain.support(96000,17000),"outside support rejected");check(w.terrain.surface_revision()==1,"cheap stable surface generation");auto t=w.terrain;t.cells[0].kind=TerrainKind::Soil;reject([&]{t.validate();},"TERRAIN_GUARD");for(unsigned k=0;k<8;k++)check(parse_terrain(terrain_name(TerrainKind(k)))==TerrainKind(k),"eight named fixed heights");auto d=draft();d.budget_bytes=1;reject([&]{create_candidate(d,defs);},"CREATION_BUDGET");d=draft();d.core_width=1009;reject([&]{create_candidate(d,defs);},"CREATION_DIMENSIONS");reject([&]{create_candidate(draft(),defs,nullptr,[]{return true;});},"CREATION_CANCELED");}
void geography(const fs::path&root,const DefinitionPackage&defs){auto b=geography_fixture();write(root/"fixture.b",b);Geography g(root/"fixture.b",sha256(b));check(g.polygon_count()==3,"all source levels");check(g.land(179200000,0)&&g.land(-180800000,0),"date-line same real polygon");check(!g.land(179600000,0)&&g.land(-180000000,0),"nested lake/island precedence");check(g.land(179000000,0),"source segment boundary inside");auto d=draft();d.kind=CreationKind::Earth;d.selection={178000000,182000000,-2000000,2000000};auto w=create_candidate(d,defs,&g);auto sample=g.sample_world_selection(d.selection,32,32);for(int z=0;z<32;z++)for(int x=0;x<32;x++)check((w.terrain.at(x+8,z+8).kind==TerrainKind::Soil)==bool(sample[size_t(z)*32+size_t(x)]),"highest preview equals candidate");check(decode_save(encode_save(w),defs).deterministic_hash()==w.deterministic_hash(),"Earth provenance and geometry save roundtrip");d.selection.north_udeg=81000000;reject([&]{create_candidate(d,defs,&g);},"EARTH_SELECTION");auto bad=sha256(b);bad[0]^=1;reject([&]{Geography missing(root/"fixture.b",bad);},"GEO_SOURCE_HASH");}
void antarctic_topology(const fs::path&root){
 Bytes b;
 ring(b,4,5,-1,{{180000000,-70000000},{90000000,-71000000},{0,-72000000},{-90000000,-71000000},{-180000000,-70000000}},true);
 ring(b,145,5,-1,{{80000000,-66000000},{82000000,-66000000},{82000000,-65000000},{80000000,-65000000},{80000000,-66000000}});
 ring(b,146,6,-1,{{100000000,-66000000},{102000000,-66000000},{102000000,-65000000},{100000000,-65000000},{100000000,-66000000}});
 write(root/"antarctic.b",b);Geography g(root/"antarctic.b",sha256(b));
 check(g.polygon_count()==2,"ice-front ordinary islands admitted, grounding-line excluded");
 check(g.land(81000000,-65500000),"ordinary closed L5 island keeps its real interior");
 check(!g.land(83000000,-65500000)&&!g.land(101000000,-65500000),"island not extended to pole; L6 not land");
 check(g.land(0,-75000000)&&g.land(179000000,-75000000)&&g.land(-179000000,-75000000),"pole-winding mainland fills south on both meridians");
 check(!g.land(0,-60000000),"polar closure does not fabricate northern land");
 auto values=g.sample({-5000000,5000000,-80000000,-73000000},10,7);
 check(std::all_of(values.begin(),values.end(),[](auto v){return v==1;}),"exact scanline samples the real polar interior");
 Bytes malformed;ring(malformed,4,5,-1,{{180000000,-70000000},{90000000,-71000000},{0,-72000000},{-90000000,-71000000},{-180000000,-70000000}});
 write(root/"bad-polar.b",malformed);reject([&]{Geography bad(root/"bad-polar.b",sha256(malformed));},"GEO_RING_INVALID");
}
void authority(const DefinitionPackage&defs){auto w=create_candidate(draft(),defs);Authority a(w,7);Envelope e{w.id,7,w.revision,1,"rename-first"};Command c{Command::Kind::RenameWorld,"Neue Ähren · 新世界"};auto before=a.world().deterministic_hash();auto p=a.prepare(e,c);check(a.world().deterministic_hash()==before,"prepare is read-only");auto receipt=a.commit(p);check(a.world().name==c.text&&a.world().tick==0&&a.world().boundary_ordinal==1,"paused commit has zero elapsed ticks");auto once=a.world().deterministic_hash();check(a.commit(p).committed_revision==receipt.committed_revision&&a.world().deterministic_hash()==once,"committed idempotency retry");c.text="Different";reject([&]{a.prepare(e,c);},"IDEMPOTENCY_CONFLICT");e.command_id="late";e.input_sequence=2;reject([&]{a.prepare(e,c);},"STALE_REVISION");e.expected_revision=a.world().revision;e.session_generation=6;reject([&]{a.prepare(e,c);},"STALE_GENERATION");e.session_generation=7;auto stale=a.prepare(e,c);a.advance_tick();reject([&]{a.commit(stale);},"STALE_REVISION");e.expected_revision=a.world().revision;e.command_id="auto-age";Command auto_age{Command::Kind::SetAgeAutomatic};auto_age.boolean=true;auto_age.light_duration_tick=2;auto_age.dark_duration_tick=3;a.commit(a.prepare(e,auto_age));auto trace=a.advance_tick();check(trace.phases.size()==11&&trace.phases[10]=="PUBLISH"&&a.world().age.remaining_tick==1,"11 barriers and age remainder");a.advance_tick();check(a.world().age.current==Age::Darkness&&a.world().age.remaining_tick==3,"automatic exact age expiry");e.expected_revision=a.world().revision;e.input_sequence=3;e.command_id="manual-age";Command manual{Command::Kind::SetAge};manual.age=Age::Light;a.commit(a.prepare(e,manual));check(!a.world().age.automatic&&a.world().age.remaining_tick==0,"manual atomically disables auto");e.expected_revision=a.world().revision;e.input_sequence=4;e.command_id="set-rule";Command rule{Command::Kind::SetRule,"hunger_consequences",false};a.commit(a.prepare(e,rule));check(!a.world().rules.at("hunger_consequences")&&a.world().population==0,"rule persist no free life");std::atomic_bool rejected=false;std::thread other([&]{try{a.advance_tick();}catch(const Error&err){rejected=err.code=="NOT_SINGLE_WRITER";}});other.join();check(rejected,"single-writer thread");}
void save_and_session(const fs::path&root,const DefinitionPackage&defs){auto w=create_candidate(draft(),defs);auto bytes=encode_save(w);check(bytes.size()>632&&std::string(bytes.begin(),bytes.begin()+8)=="SONNSAV1"&&bytes[8]==1&&bytes[16]==8,"actual 120B header eight64B entries");check(bytes[120]==1&&bytes[184]==2&&bytes[248]==3,"entry width64");check(decode_save(bytes,defs).deterministic_hash()==w.deterministic_hash(),"canonical complete save readback");auto corrupt=bytes;corrupt.back()^=1;reject([&]{decode_save(corrupt,defs);},"SAVE_HASH");corrupt=bytes;corrupt[8]=2;reject([&]{decode_save(corrupt,defs);},"SAVE_VERSION");auto wrong=defs;wrong.hash[0]^=1;reject([&]{decode_save(bytes,wrong);},"DEFINITION_MISSING");wrong=defs;wrong.asset_hash[0]^=1;reject([&]{decode_save(bytes,wrong);},"ASSET_MISSING");
 SaveStore store(root/"save");auto first=store.save(w,defs);check(first.status==SaveStatus::Committed&&store.continue_world(defs)->deterministic_hash()==w.deterministic_hash(),"durable checkpoint before Continue");auto changed=w;changed.name="Changed";changed.revision=2;
 for(auto fault:{SaveFault::BeforeWrite,SaveFault::ShortWrite,SaveFault::FileFlush,SaveFault::Readback,SaveFault::RenameCheckpoint,SaveFault::CheckpointDirectoryFlush,SaveFault::PointerWrite,SaveFault::PointerRename}){auto result=store.save(changed,defs,fault);check(result.status==SaveStatus::Failed,"precommit failure");check(store.continue_world(defs)->id==w.id&&store.continue_world(defs)->name==w.name,"old Continue preserved");}
 auto unknown=store.save(changed,defs,SaveFault::PointerDirectoryFlush);check(unknown.status==SaveStatus::DurabilityUnknown&&unknown.code=="DURABILITY_UNKNOWN","postrename unknown durability");SaveStore restart(root/"save");check(restart.continue_world(defs)->name==w.name,"restart does not trust pending success bit");check(restart.recover(unknown.filename,defs).name==changed.name,"explicit orphan recovery");reject([&]{restart.recover("../steal.sonnsave",defs);},"UNSAFE_PATH");WorldSession session;session.load_continue(store,defs);auto original=session.active()->world().deterministic_hash();auto d=draft();d.world_id=uuid_from_hex("22222222222222222222222222222222");d=session.begin(d);auto candidate=create_candidate(d,defs);session.cancel();Checkpoint result;check(!session.publish(d,candidate,store,defs,result)&&result.code=="STALE_GENERATION"&&session.active()->world().deterministic_hash()==original,"canceled late candidate cannot replace World");d=session.begin(d);candidate=create_candidate(d,defs);auto before_generation=session.generation();check(!session.publish(d,candidate,store,defs,result,SaveFault::PointerDirectoryFlush)&&session.active()->world().deterministic_hash()==original&&session.generation()==before_generation,"uncertain firstsave never publishes new World");check(session.publish(d,candidate,store,defs,result)&&session.active()->world().id==d.world_id&&session.generation()>before_generation&&!session.accepts(d),"same current candidate can safely retry");session.load_checkpoint(first.filename,store,defs);check(session.active()->world().id==w.id&&store.continue_world(defs)->id==w.id,"explicit selected load durably republishes Continue");auto generation=session.generation();session.return_to_menu();check(!session.active()&&session.generation()>generation&&!session.accepts(d),"menu isolates generation");}
void save_replacement_recovery(const fs::path&root,const DefinitionPackage&defs){
 auto old=create_candidate(draft(),defs);SaveStore store(root/"replacement");auto first=store.save(old,defs);check(first.status==SaveStatus::Committed,"old pack checkpoint");
 auto old_pointer=read_file(root/"replacement/continue.json");auto old_checkpoint=read_file(root/"replacement"/first.filename);
 auto next_defs=defs;next_defs.asset_hash[0]^=1;auto d=draft();d.world_id[0]^=1;auto next=create_candidate(d,next_defs);
 reject([&]{store.continue_world(next_defs);},"ASSET_MISSING");auto failed=store.save(next,next_defs,SaveFault::PointerRename);
 check(failed.status==SaveStatus::Failed&&read_file(root/"replacement/continue.json")==old_pointer,"incompatible old Continue preserved on failed replacement");
 check(store.continue_world(defs)->id==old.id,"old package can still decode retained pointer");
 auto published=store.save(next,next_defs);check(published.status==SaveStatus::Committed&&store.continue_world(next_defs)->id==next.id,"new package creates world without loading incompatible Continue");
 check(read_file(root/"replacement/continue_previous.json")==old_pointer&&read_file(root/"replacement"/first.filename)==old_checkpoint,"prior pointer and checkpoint bytes remain unchanged");
 write(root/"replacement/continue.json","{broken pointer");auto broken_pointer=read_file(root/"replacement/continue.json");
 reject([&]{store.continue_world(next_defs);},"INVALID_JSON");auto uncertain=store.save(next,next_defs,SaveFault::PointerDirectoryFlush);
 check(uncertain.status==SaveStatus::DurabilityUnknown,"bad pointer replacement still honours durability uncertainty");
 check(read_file(root/"replacement/continue_previous.json")==broken_pointer,"malformed prior pointer retained verbatim for recovery");
 reject([&]{store.continue_world(next_defs);},"INVALID_JSON");WorldSession recovered;recovered.load_checkpoint(published.filename,store,next_defs);
 check(recovered.active()->world().id==next.id&&store.continue_world(next_defs)->id==next.id,"explicit valid checkpoint recovery bypasses damaged old pointer");
 check(read_file(root/"replacement/continue_previous.json")==broken_pointer,"explicit recovery preserves damaged evidence instead of deleting it");
 for(auto fault:{SaveFault::PendingRemove,SaveFault::PendingDirectoryFlush}){
  SaveStore gated(root/(fault==SaveFault::PendingRemove?"pending-remove":"pending-flush"));auto baseline=gated.save(old,defs);check(baseline.status==SaveStatus::Committed,"reader gate fixture committed");
  WorldSession live;live.load_continue(gated,defs);auto before=live.active()->world().deterministic_hash();auto generation=live.generation();auto fresh=draft();fresh.world_id[0]^=2;fresh=live.begin(fresh);auto candidate=create_candidate(fresh,defs);Checkpoint outcome;
  check(!live.publish(fresh,candidate,gated,defs,outcome,fault)&&outcome.status==SaveStatus::DurabilityUnknown,"reader gate failure cannot claim committed publication");
  check(live.generation()==generation&&live.active()->world().deterministic_hash()==before,"uncertain gate preserves in-memory world and session");
  check(gated.recover(outcome.filename,defs).id==candidate.id,"uncertain candidate remains explicitly recoverable");
  check(outcome.reader_gate_restored&&outcome.reader_gate_error.empty(),"uncertain publication durably reinstalls reader gate");
  check(gated.continue_world(defs)->id==old.id,"both reader gate failure points retain old in-process Continue");
  SaveStore reopened(gated.root());check(reopened.continue_world(defs)->id==old.id,"new store reads old Continue after recovery gate flush");
  auto failed_retry=gated.save(candidate,defs,SaveFault::BeforeWrite);check(failed_retry.status==SaveStatus::Failed&&gated.continue_world(defs)->id==old.id,"failed retry does not clear conservative reader latch");
  check(live.publish(fresh,candidate,gated,defs,outcome)&&outcome.status==SaveStatus::Committed,"same candidate retry completes durable publication");
  check(live.generation()>generation&&gated.continue_world(defs)->id==candidate.id&&!fs::exists(gated.root()/"pending.json"),"successful retry clears latch and publishes candidate Continue");
  SaveStore after_retry(gated.root());check(after_retry.continue_world(defs)->id==candidate.id,"successful retry new Continue persists across store reconstruction");
 }
 SaveStore failed_gate(root/"pending-recovery-flush");auto baseline=failed_gate.save(old,defs);check(baseline.status==SaveStatus::Committed,"recovery flush fixture committed");auto prior=read_file(failed_gate.root()/"continue.json");
 auto fresh=draft();fresh.world_id[0]^=3;auto candidate=create_candidate(fresh,defs);auto unknown=failed_gate.save(candidate,defs,SaveFault::PendingDirectoryFlushAndRecoveryFlush);
 check(unknown.status==SaveStatus::DurabilityUnknown&&!unknown.reader_gate_restored&&unknown.reader_gate_error.find("SAVE_FLUSH")!=std::string::npos,"failed gate reinstallation is reported without claiming durable rollback");
 check(!fs::exists(failed_gate.root()/"pending.json")&&read_file(failed_gate.root()/"continue_previous.json")==prior,"failed gate flush preserves previous pointer bytes without falsely claiming installed gate");
 check(failed_gate.continue_world(defs)->id==old.id&&failed_gate.recover(unknown.filename,defs).id==candidate.id,"in-process latch rejects unconfirmed Continue while candidate remains recoverable");
 auto retry=failed_gate.save(candidate,defs);check(retry.status==SaveStatus::Committed&&failed_gate.continue_world(defs)->id==candidate.id,"successful retry clears latch after gate recovery itself failed");
 check(read_file(failed_gate.root()/"continue_previous.json")==prior,"retry preserves actual old pointer instead of promoting unconfirmed disk pointer to previous slot");
}
}
int main(int argc,char**argv){fs::path root=fs::temp_directory_path()/("sonnheide-core-test-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));try{auto defs=definitions(root);json_and_hash();rng();terrain(defs);geography(root,defs);antarctic_topology(root);authority(defs);save_and_session(root,defs);save_replacement_recovery(root,defs);write(root/"definition.json","bad");reject([&]{admit_definitions(root/"definitions.json",root);},"DEFINITION_HASH");
 if(argc==3){Geography actual(fs::path(argv[2])/"geo/gshhs_f.b",hash_from_hex("af9215d58ebc525b2d09654a89959829f09e6edc457f3666759cded37be4ecf6"));check(fs::exists(fs::path(argv[1])/"data/geo/gshhg_sources.lock.json"),"official source lock present");check(actual.polygon_count()==188268,"complete official source except 344 excluded grounding-line rings");check(actual.land(0,-80000000),"official pole-containing ice-front mainland");check(actual.land(-67658936,-66640321),"official ordinary closed L5 island boundary");check(actual.land(13405000,52520000),"Berlin official land");check(!actual.land(-30000000,30000000),"Atlantic official water");auto d=draft();d.kind=CreationKind::Earth;d.selection={-6000000,2000000,49000000,55000000};d.core_width=128;auto earth=create_candidate(d,defs,&actual);check(earth.terrain.width==144&&earth.terrain.height==112,"exact Earth aspect and guard");check(decode_save(encode_save(earth),defs).deterministic_hash()==earth.deterministic_hash(),"real-source Earth save readback");}
 fs::remove_all(root);std::cout<<"Core S00/S01: "<<checks<<" invariant checks passed\n";return 0;
 }catch(const std::exception&e){std::cerr<<"Core check failed: "<<e.what()<<"\nfixtures: "<<root<<'\n';return 1;}}
