#include "sonnheide.hpp"
#include <algorithm>
#include <bit>
#include <fstream>
#include <limits>
namespace sonn {
namespace {
constexpr std::array<uint32_t,64> K{0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};
void block(std::array<uint32_t,8>& h,const uint8_t* p){uint32_t w[64];for(int i=0;i<16;i++)w[i]=(uint32_t(p[i*4])<<24)|(uint32_t(p[i*4+1])<<16)|(uint32_t(p[i*4+2])<<8)|p[i*4+3];for(int i=16;i<64;i++){auto a=w[i-15],b=w[i-2];w[i]=w[i-16]+(std::rotr(a,7)^std::rotr(a,18)^(a>>3))+w[i-7]+(std::rotr(b,17)^std::rotr(b,19)^(b>>10));}auto v=h;for(int i=0;i<64;i++){auto t1=v[7]+(std::rotr(v[4],6)^std::rotr(v[4],11)^std::rotr(v[4],25))+((v[4]&v[5])^(~v[4]&v[6]))+K[i]+w[i];auto t2=(std::rotr(v[0],2)^std::rotr(v[0],13)^std::rotr(v[0],22))+((v[0]&v[1])^(v[0]&v[2])^(v[1]&v[2]));for(int j=7;j>0;j--)v[j]=v[j-1];v[4]+=t1;v[0]=t1+t2;}for(int i=0;i<8;i++)h[i]+=v[i];}
void le(Bytes& b,uint64_t v,unsigned n){for(unsigned i=0;i<n;i++)b.push_back(uint8_t(v>>(8*i)));}
#include "ref_registry.inc"
std::string_view scope(std::string_view k){auto it=std::lower_bound(std::begin(kind_scopes),std::end(kind_scopes),k,[](auto p,auto x){return p.first<x;});return it!=std::end(kind_scopes)&&it->first==k?it->second:std::string_view{};}
std::filesystem::path safe_member(const std::filesystem::path& root,const std::string& name){std::filesystem::path rel(name);if(rel.empty()||rel.is_absolute()||name.find(':')!=std::string::npos||name.find('\\')!=std::string::npos)throw Error("UNSAFE_PATH",name);for(const auto& p:rel)if(p==".."||p==".")throw Error("UNSAFE_PATH",name);auto base=std::filesystem::weakly_canonical(root),full=std::filesystem::weakly_canonical(base/rel);auto a=base.begin(),b=full.begin();for(;a!=base.end();++a,++b)if(b==full.end()||*a!=*b)throw Error("UNSAFE_PATH",name);return full;}
}
void Sha256Stream::update(std::span<const uint8_t> bytes){
 if(uint64_t(bytes.size())>UINT64_MAX/8-total_bytes_)throw Error("HASH_LIMIT","SHA256 byte length");total_bytes_+=uint64_t(bytes.size());size_t pos=0;
 if(buffered_bytes_){size_t n=std::min(size_t(64)-buffered_bytes_,bytes.size());std::copy_n(bytes.begin(),n,buffered_.begin()+ptrdiff_t(buffered_bytes_));buffered_bytes_+=n;pos+=n;if(buffered_bytes_==64){block(state_,buffered_.data());buffered_bytes_=0;}}
 for(;bytes.size()-pos>=64;pos+=64)block(state_,bytes.data()+pos);
 if(pos<bytes.size()){buffered_bytes_=bytes.size()-pos;std::copy(bytes.begin()+ptrdiff_t(pos),bytes.end(),buffered_.begin());}
}
Hash Sha256Stream::finish()const{
 auto state=state_;std::array<uint8_t,128>tail{};std::copy_n(buffered_.begin(),buffered_bytes_,tail.begin());tail[buffered_bytes_]=0x80;size_t length=buffered_bytes_<56?64:128;uint64_t bits=total_bytes_*8;for(unsigned j=0;j<8;j++)tail[length-1-j]=uint8_t(bits>>(8*j));block(state,tail.data());if(length==128)block(state,tail.data()+64);Hash out{};for(size_t j=0;j<8;j++)for(size_t k=0;k<4;k++)out[j*4+k]=uint8_t(state[j]>>(24-8*k));return out;
}
Hash sha256(std::span<const uint8_t> bytes){Sha256Stream stream;stream.update(bytes);return stream.finish();}
Hash sha256(std::string_view s){return sha256(std::span(reinterpret_cast<const uint8_t*>(s.data()),s.size()));}
std::string hex(std::span<const uint8_t>b){constexpr char h[]="0123456789abcdef";std::string s;s.reserve(b.size()*2);for(auto v:b){s+=h[v>>4];s+=h[v&15];}return s;}
Bytes unhex(std::string_view s){if(s.size()%2)throw Error("INVALID_HEX","length");Bytes b;for(size_t i=0;i<s.size();i+=2){auto digit=[](char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;throw Error("INVALID_HEX","lowercase required");};b.push_back(uint8_t(digit(s[i])*16+digit(s[i+1])));}return b;}
Hash hash_from_hex(std::string_view s){if(s.size()!=64)throw Error("INVALID_HASH","length");Hash h{};auto b=unhex(s);std::copy(b.begin(),b.end(),h.begin());return h;}
Uuid uuid_from_hex(std::string_view s){if(s.size()!=32)throw Error("INVALID_UUID","length");Uuid h{};auto b=unhex(s);std::copy(b.begin(),b.end(),h.begin());return h;}
Bytes read_file(const std::filesystem::path&p,uint64_t max){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)throw Error("FILE_OPEN",p.string());auto length=f.tellg();if(length<0||uint64_t(length)>max)throw Error("FILE_LIMIT",p.string());Bytes b(static_cast<size_t>(length));f.seekg(0);if(!b.empty()&&!f.read(reinterpret_cast<char*>(b.data()),std::streamsize(b.size())))throw Error("FILE_READ",p.string());return b;}
bool registered_kind(std::string_view k){return !scope(k).empty();}
std::string canonical_kind(std::string_view k){static const std::map<std::string_view,std::string_view> aliases{{"person","actor"},{"animal","actor"},{"city","settlement"},{"empire","state"},{"port","building"},{"ship","vehicle"},{"equipment","item"},{"skill","actor"},{"thermal_exposure","actor"}};auto i=aliases.find(k);if(i!=aliases.end())return std::string(i->second);if(!registered_kind(k))throw Error("UNKNOWN_REF_KIND",std::string(k));return std::string(k);}
Json ref_json(const Ref&r){if(!registered_kind(r.kind)||!r.generation)throw Error("INVALID_REF","kind or generation");std::array<uint8_t,8>b{};for(int i=0;i<8;i++)b[size_t(i)]=uint8_t(r.stable_id>>(56-8*i));return Json::Object{{"world_id",hex(r.world_id)},{"kind",r.kind},{"stable_id",hex(b)},{"generation",int64_t(r.generation)}};}
Ref parse_ref(const Json&j){if(j.object().size()!=4)throw Error("INVALID_REF","fields");Ref r;r.world_id=uuid_from_hex(j.at("world_id").string());r.kind=j.at("kind").string();if(!registered_kind(r.kind))throw Error("UNKNOWN_REF_KIND",r.kind);auto s=j.at("stable_id").string();if(s.size()!=16)throw Error("INVALID_REF","stable id");for(auto v:unhex(s))r.stable_id=(r.stable_id<<8)|v;auto g=j.at("generation").integer();if(g<1||g>4294967295LL)throw Error("INVALID_REF","generation");r.generation=uint32_t(g);return r;}
Bytes rng_preimage(const Hash&seed,std::string_view domain,const Ref&r,const Hash&defs,uint64_t event,uint64_t draw,uint64_t attempt){if(domain.empty()||domain.size()>64||domain[0]<'a'||domain[0]>'z')throw Error("RNG_DOMAIN","syntax");for(char c:domain)if(!((c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'||c=='.'))throw Error("RNG_DOMAIN","syntax");auto sc=scope(r.kind);if(sc.empty()||sc=="local_profile"||sc=="trusted_session"||sc=="immutable_definition"||!r.generation)throw Error("RNG_REF","canonical committed subject required");Bytes b{'S','O','N','N','R','N','G','1'};b.insert(b.end(),seed.begin(),seed.end());le(b,domain.size(),2);b.insert(b.end(),domain.begin(),domain.end());b.insert(b.end(),r.world_id.begin(),r.world_id.end());le(b,r.kind.size(),2);b.insert(b.end(),r.kind.begin(),r.kind.end());le(b,r.stable_id,8);le(b,r.generation,4);b.insert(b.end(),defs.begin(),defs.end());le(b,event,8);le(b,draw,8);le(b,attempt,8);return b;}
std::optional<uint64_t> reduce_uniform_raw(uint64_t raw,uint64_t n){if(!n||n>uint64_t(INT64_MAX))throw Error("RNG_BOUND","1..INT64_MAX");uint64_t tail=(uint64_t(0)-n)%n;if(tail&&raw>UINT64_MAX-tail)return {};return raw%n;}
RngDraw uniform_rng(const Hash&seed,std::string_view d,const Ref&r,const Hash&defs,uint64_t event,uint64_t draw,uint64_t n){if(!n||n>uint64_t(INT64_MAX))throw Error("RNG_BOUND","1..INT64_MAX");if(draw==UINT64_MAX)throw Error("RNG_COUNTER_OVERFLOW","draw");for(uint64_t a=0;a<4096;a++){auto h=sha256(rng_preimage(seed,d,r,defs,event,draw,a));uint64_t raw=0;for(unsigned i=0;i<8;i++)raw|=uint64_t(h[i])<<(8*i);if(auto value=reduce_uniform_raw(raw,n))return {*value,draw+1,a+1};}throw Error("RNG_REJECTION_LIMIT","4096 attempts");}
DefinitionPackage admit_definitions(const std::filesystem::path&manifest,const std::filesystem::path&root){auto bytes=read_file(manifest,16777216);auto j=parse_json(std::string_view(reinterpret_cast<char*>(bytes.data()),bytes.size()));if(j.object().size()!=2||j.at("format").string()!="SonnDefinitions1")throw Error("DEFINITION_FORMAT","manifest");DefinitionPackage out{sha256(canonical_json(j)),{},j,std::filesystem::weakly_canonical(root),{}};std::string previous;for(auto& entry:j.at("files").array()){if(entry.object().size()!=2)throw Error("DEFINITION_FORMAT","entry");auto path=entry.at("path").string();if(!previous.empty()&&path<=previous)throw Error("DEFINITION_FORMAT","sorted unique files");previous=path;auto b=read_file(safe_member(root,path));if(sha256(b)!=hash_from_hex(entry.at("sha256").string()))throw Error("DEFINITION_HASH",path);out.files.push_back(path);}if(out.files.empty())throw Error("DEFINITION_FORMAT","empty package");return out;}
Hash admit_assets(const std::filesystem::path&manifest,const std::filesystem::path&root){auto bytes=read_file(manifest,16777216);auto j=parse_json(std::string_view(reinterpret_cast<char*>(bytes.data()),bytes.size()));if(j.object().size()!=2||j.at("format").string()!="SonnAssets1")throw Error("ASSET_FORMAT","manifest");std::string previous;for(auto& entry:j.at("files").array()){if(entry.object().size()!=2)throw Error("ASSET_FORMAT","entry");auto path=entry.at("path").string();if(!previous.empty()&&path<=previous)throw Error("ASSET_FORMAT","sorted unique files");previous=path;auto b=read_file(safe_member(root,path));if(sha256(b)!=hash_from_hex(entry.at("sha256").string()))throw Error("ASSET_HASH",path);}if(previous.empty())throw Error("ASSET_FORMAT","empty package");return sha256(canonical_json(j));}
} // sonn
