#include "sonnheide.hpp"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>
#include <set>
#include <tuple>
namespace sonn {
namespace {
bool cell_less(const Cell&a,const Cell&b){return std::tie(a.kind,a.theme,a.revision)<std::tie(b.kind,b.theme,b.revision);}
bool visible_same(const Cell&a,const Cell&b){return a.kind==b.kind&&a.theme==b.theme;}
void valid_cell(const Cell&c){if(size_t(c.kind)>=8||c.theme>7||!c.revision||c.revision>uint64_t(INT64_MAX))throw Error("TERRAIN_PROFILE","cell");}
uint8_t bits_for(size_t n){return n<=2?1:n<=4?2:n<=16?4:n<=256?8:12;}
void require_query_geometry(const Terrain&t){if(t.width<=0||t.height<=0||t.width>maximum_core_cells+16||t.height>maximum_core_cells+16||(t.profile==1?((t.cell_mm!=250&&t.cell_mm!=2000)||t.width>1024||t.height>1024||t.cells.size()!=size_t(t.width)*t.height):(t.profile!=2||t.cell_mm!=2000||t.rows.size()!=size_t(t.height))))throw Error("TERRAIN_PROFILE","query requires admitted geometry");}
void range(const Terrain&t,int32_t sx,int32_t sz,int32_t&nx,int32_t&nz){require_query_geometry(t);if(sx<0||sz<0||sx>t.width||sz>t.height)throw Error("OUTSIDE_WORLD","mesh range");if(nx<0)nx=t.width-sx;if(nz<0)nz=t.height-sz;if(nx<0||nz<0||int64_t(sx)+nx>t.width||int64_t(sz)+nz>t.height)throw Error("OUTSIDE_WORLD","mesh range");}
void quad(Mesh&m,std::array<Vec3,4>p,Vec3 n,const Cell&c){constexpr size_t budget=67108864;if((m.vertices.size()+4)*sizeof(MeshVertex)+(m.indices.size()+6)*sizeof(uint32_t)>budget)throw Error("MESH_LIMIT","request smaller resident rectangle");auto b=uint32_t(m.vertices.size());constexpr float uv[4][2]{{0,0},{0,1},{1,1},{1,0}};for(size_t i=0;i<4;i++)m.vertices.push_back({float(p[i].x),float(p[i].y),float(p[i].z),float(n.x),float(n.y),float(n.z),uv[i][0],uv[i][1],uint8_t(c.kind),c.theme,uint8_t(terrain_is_water(c.kind))});m.indices.insert(m.indices.end(),{b,b+1,b+2,b,b+2,b+3});}
void top(Mesh&m,const Terrain&t,double x0,double z0,double x1,double z1,const Cell&c){double y=t.height_for(c.kind)/1000.0;quad(m,{Vec3{x0,y,z0},Vec3{x0,y,z1},Vec3{x1,y,z1},Vec3{x1,y,z0}},{0,1,0},c);}
}
bool terrain_is_water(TerrainKind k){if(size_t(k)>=8)throw Error("TERRAIN_KIND","index");return size_t(k)<3;}
std::string_view terrain_name(TerrainKind k){constexpr std::array<std::string_view,8>n{"deep_ocean","close_ocean","shallow_water","sand","soil","hill","mountain","high_peak"};auto i=size_t(k);if(i>=n.size())throw Error("TERRAIN_KIND","index");return n[i];}
TerrainKind parse_terrain(std::string_view s){for(unsigned i=0;i<8;i++)if(terrain_name(TerrainKind(i))==s)return TerrainKind(i);throw Error("TERRAIN_KIND",std::string(s));}
namespace {
uint8_t selector_bits(size_t n){return n<=1?0:n<=2?1:n<=4?2:n<=16?4:6;}
uint32_t packed_at(std::span<const uint8_t> bytes,size_t index,unsigned bits){if(!bits)return 0;size_t bit=index*bits,byte=bit/8;if(byte>=bytes.size())throw Error("TERRAIN_PATCH","selector bytes");uint32_t word=bytes[byte];if(byte+1<bytes.size())word|=uint32_t(bytes[byte+1])<<8;if(byte+2<bytes.size())word|=uint32_t(bytes[byte+2])<<16;return (word>>(bit%8))&((1u<<bits)-1);}
uint64_t span_word(unsigned lo,unsigned hi){if(lo>hi||hi>64)throw Error("TERRAIN_PATCH","0..64 half-open span");if(lo==hi){if(lo)throw Error("TERRAIN_PATCH","canonical empty span");return 0;}return hi-lo==64?UINT64_MAX:((uint64_t(1)<<(hi-lo))-1)<<lo;}
}
uint64_t FinePatch::row_bits(int32_t row)const{
 if(row<0||row>=64||index_bits!=1||palette.size()!=2)throw Error("TERRAIN_PATCH","binary row");
 if(encoding==0){if(indices.size()!=512)throw Error("TERRAIN_PATCH","packed binary bytes");uint64_t word=0;for(unsigned i=0;i<8;i++)word|=uint64_t(indices[size_t(row)*8+i])<<(8*i);return word;}
 if(encoding==1){if(indices.size()!=128)throw Error("TERRAIN_PATCH","fixed span bytes");return span_word(indices[size_t(row)*2],indices[size_t(row)*2+1]);}
 if(encoding==2){if(indices.size()<130||indices.size()>512)throw Error("TERRAIN_PATCH","row-offset bytes");auto off=[&](int z){return unsigned(indices[size_t(z)*2])|(unsigned(indices[size_t(z)*2+1])<<8);};unsigned lo=off(row),hi=off(row+1);if(lo>hi||hi>indices.size()-130||(lo&1)||(hi&1))throw Error("TERRAIN_PATCH","row offsets");uint64_t word=0;unsigned previous=0;for(unsigned p=lo;p<hi;p+=2){unsigned a=indices[130+p],b=indices[131+p];if(a>=b||b>64||(p>lo&&a<=previous))throw Error("TERRAIN_PATCH","sorted disjoint nonadjacent spans");word|=span_word(a,b);previous=b;}return word;}
 if(encoding==3||encoding==4){if(indices.empty())throw Error("TERRAIN_PATCH","dictionary header");size_t n=size_t(indices[0])+1;if(n>64)throw Error("TERRAIN_PATCH","dictionary size");auto bits=selector_bits(n);size_t selector_bytes=64*size_t(bits)/8,base=1+selector_bytes;if(indices.size()!=base+n*(encoding==3?2:8))throw Error("TERRAIN_PATCH","dictionary bytes");auto slot=packed_at(std::span<const uint8_t>(indices).subspan(1,selector_bytes),size_t(row),bits);if(slot>=n)throw Error("TERRAIN_PATCH","dictionary selector");if(encoding==3)return span_word(indices[base+slot*2],indices[base+slot*2+1]);uint64_t word=0;for(unsigned b=0;b<8;b++)word|=uint64_t(indices[base+slot*8+b])<<(8*b);return word;}
 throw Error("TERRAIN_PATCH","unknown encoding");
}
Bytes FinePatch::canonical_indices()const{if(!encoding)return indices;if(index_bits!=1||palette.size()!=2)throw Error("TERRAIN_PATCH","binary codec palette");Bytes raw;raw.reserve(512);for(int row=0;row<64;row++){uint64_t word=row_bits(row);for(unsigned b=0;b<8;b++)raw.push_back(uint8_t(word>>(8*b)));}return raw;}
std::array<uint16_t,64> FinePatch::coverage_counts()const{
 std::array<uint16_t,64>counts{};auto add=[&](const Cell&c,unsigned count){valid_cell(c);counts[size_t(c.kind)*8+c.theme]=uint16_t(counts[size_t(c.kind)*8+c.theme]+count);};
 if(index_bits==1&&palette.size()==2){unsigned ones=0;for(int row=0;row<64;row++)ones+=std::popcount(row_bits(row));add(palette[0],4096-ones);add(palette[1],ones);}else for(size_t i=0;i<4096;i++)add(at(i),1);return counts;
}
void FinePatch::compress_binary(){
 if(index_bits!=1||palette.size()!=2)return;std::array<uint64_t,64> words{};for(int row=0;row<64;row++)words[size_t(row)]=row_bits(row);
 Bytes best;best.reserve(512);for(auto word:words)for(unsigned b=0;b<8;b++)best.push_back(uint8_t(word>>(8*b)));uint8_t best_encoding=0;
 Bytes fixed,spans;std::array<uint16_t,65>offsets{};bool single=true;std::vector<std::pair<uint8_t,uint8_t>>row_pairs;row_pairs.reserve(64);
 for(int row=0;row<64;row++){auto word=words[size_t(row)];offsets[size_t(row)]=uint16_t(spans.size());unsigned runs=0;uint8_t single_lo=0,single_hi=0;for(unsigned x=0;x<64;){if(((word>>x)&1)==0){++x;continue;}unsigned lo=x++;while(x<64&&((word>>x)&1))++x;spans.push_back(uint8_t(lo));spans.push_back(uint8_t(x));single_lo=uint8_t(lo);single_hi=uint8_t(x);++runs;}if(runs>1)single=false;row_pairs.emplace_back(single_lo,single_hi);fixed.push_back(single_lo);fixed.push_back(single_hi);}offsets[64]=uint16_t(spans.size());
 auto choose=[&](uint8_t code,Bytes data){if(data.size()<best.size()){best=std::move(data);best_encoding=code;}};
 if(single)choose(1,std::move(fixed));
 Bytes variable;variable.reserve(130+spans.size());for(auto off:offsets){variable.push_back(uint8_t(off));variable.push_back(uint8_t(off>>8));}variable.insert(variable.end(),spans.begin(),spans.end());choose(2,std::move(variable));
 if(single){auto unique=row_pairs;std::sort(unique.begin(),unique.end());unique.erase(std::unique(unique.begin(),unique.end()),unique.end());auto bits=selector_bits(unique.size());Bytes dictionary(1+64*size_t(bits)/8,0);dictionary[0]=uint8_t(unique.size()-1);for(size_t row=0;row<64;row++){auto slot=uint32_t(std::lower_bound(unique.begin(),unique.end(),row_pairs[row])-unique.begin());for(unsigned bit=0;bit<bits;bit++)if(slot&(1u<<bit))dictionary[1+(row*bits+bit)/8]|=uint8_t(1u<<((row*bits+bit)%8));}for(auto [lo,hi]:unique){dictionary.push_back(lo);dictionary.push_back(hi);}choose(3,std::move(dictionary));}
 auto unique_words=words;std::sort(unique_words.begin(),unique_words.end());size_t count=size_t(std::unique(unique_words.begin(),unique_words.end())-unique_words.begin());auto word_bits=selector_bits(count);Bytes dictionary(1+64*size_t(word_bits)/8,0);dictionary[0]=uint8_t(count-1);for(size_t row=0;row<64;row++){auto slot=uint32_t(std::lower_bound(unique_words.begin(),unique_words.begin()+ptrdiff_t(count),words[row])-unique_words.begin());for(unsigned bit=0;bit<word_bits;bit++)if(slot&(1u<<bit))dictionary[1+(row*word_bits+bit)/8]|=uint8_t(1u<<((row*word_bits+bit)%8));}for(size_t j=0;j<count;j++)for(unsigned b=0;b<8;b++)dictionary.push_back(uint8_t(unique_words[j]>>(8*b)));choose(4,std::move(dictionary));
 encoding=best_encoding;indices=std::move(best);Bytes(indices).swap(indices);
}
const Cell& FinePatch::at(size_t i)const{if(i>=4096||index_bits==0||index_bits>12)throw Error("TERRAIN_PATCH","packed index");uint32_t idx;if(encoding)idx=uint32_t((row_bits(int32_t(i/64))>>(i%64))&1);else{if(indices.size()!=4096*size_t(index_bits)/8)throw Error("TERRAIN_PATCH","packed bytes");idx=packed_at(indices,i,index_bits);}if(idx>=palette.size())throw Error("TERRAIN_PATCH","palette index");return palette[idx];}
FinePatch FinePatch::pack(std::span<const Cell>v){if(v.size()!=4096)throw Error("TERRAIN_PATCH","64 squared samples");FinePatch p;p.palette.assign(v.begin(),v.end());for(auto&c:p.palette)valid_cell(c);std::sort(p.palette.begin(),p.palette.end(),cell_less);p.palette.erase(std::unique(p.palette.begin(),p.palette.end()),p.palette.end());std::vector<Cell>(p.palette).swap(p.palette);p.index_bits=bits_for(p.palette.size());p.indices.assign(4096*size_t(p.index_bits)/8,0);for(size_t i=0;i<v.size();i++){auto idx=uint32_t(std::lower_bound(p.palette.begin(),p.palette.end(),v[i],cell_less)-p.palette.begin());size_t bit=i*p.index_bits;for(unsigned j=0;j<p.index_bits;j++)if(idx&(1u<<j))p.indices[(bit+j)/8]|=uint8_t(1u<<((bit+j)%8));}p.compress_binary();return p;}
void FinePatch::validate()const{
 if(palette.size()<2||palette.size()>4096||index_bits!=bits_for(palette.size())||encoding>4||(!encoding&&indices.size()!=4096*size_t(index_bits)/8)||(encoding&&(index_bits!=1||palette.size()!=2||indices.size()>512)))throw Error("TERRAIN_PATCH","canonical palette/width/codec");std::vector<bool>used(palette.size());for(size_t i=0;i<palette.size();i++){valid_cell(palette[i]);if(i&&!cell_less(palette[i-1],palette[i]))throw Error("TERRAIN_PATCH","sorted unique palette");}
 if(index_bits==1&&palette.size()==2){for(int row=0;row<64;row++){auto word=row_bits(row);used[0]=used[0]||word!=UINT64_MAX;used[1]=used[1]||word!=0;}if(encoding==2){if(indices[0]||indices[1])throw Error("TERRAIN_PATCH","row offsets origin");size_t end=unsigned(indices[128])|(unsigned(indices[129])<<8);if(end+130!=indices.size())throw Error("TERRAIN_PATCH","row offsets tail");}if(encoding==3||encoding==4){size_t n=size_t(indices[0])+1,bits=selector_bits(n),selector_bytes=64*bits/8,base=1+selector_bytes;std::vector<bool>rows_used(n);std::pair<uint8_t,uint8_t>previous{};uint64_t previous_word=0;for(size_t j=0;j<n;j++){if(encoding==3){std::pair pair{indices[base+j*2],indices[base+j*2+1]};(void)span_word(pair.first,pair.second);if(j&&pair<=previous)throw Error("TERRAIN_PATCH","sorted unique span dictionary");previous=pair;}else{uint64_t word=0;for(unsigned b=0;b<8;b++)word|=uint64_t(indices[base+j*8+b])<<(8*b);if(j&&word<=previous_word)throw Error("TERRAIN_PATCH","sorted unique word dictionary");previous_word=word;}}for(size_t row=0;row<64;row++)rows_used[packed_at(std::span<const uint8_t>(indices).subspan(1,selector_bytes),row,unsigned(bits))]=true;if(std::find(rows_used.begin(),rows_used.end(),false)!=rows_used.end())throw Error("TERRAIN_PATCH","unused span dictionary row");}}
 else for(size_t i=0;i<4096;i++){auto&c=at(i);used[size_t(&c-palette.data())]=true;}if(std::find(used.begin(),used.end(),false)!=used.end())throw Error("TERRAIN_PATCH","unused palette entry");
}
const Cell& Terrain::at(int32_t x,int32_t z)const{if(x<0||z<0||x>=width||z>=height)throw Error("OUTSIDE_WORLD","cell");if(profile==1)return cells.at(size_t(z)*width+x);auto&r=rows.at(size_t(z));auto i=std::upper_bound(r.begin(),r.end(),x,[](int32_t p,const CellRun&v){return p<v.end_x;});if(i==r.end())throw Error("TERRAIN_PROFILE","RLE coverage");return i->value;}
bool Terrain::editable(int32_t x,int32_t z)const{return x>=guard&&z>=guard&&x<width-guard&&z<height-guard;}
bool Terrain::has_fine_patch(int32_t x,int32_t z)const{if(x<0||z<0||x>=width||z>=height)throw Error("OUTSIDE_WORLD","patch");return profile==2&&fine_patches.contains(uint64_t(z)*uint64_t(width)+uint64_t(x));}
const Cell& Terrain::sample_cell(int32_t x,int32_t z,int32_t mx,int32_t mz)const{auto&coarse=at(x,z);int d=micro_divisions();if(mx<0||mz<0||mx>=d||mz>=d)throw Error("OUTSIDE_WORLD","microcell");if(profile==2){auto i=fine_patches.find(uint64_t(z)*width+x);if(i!=fine_patches.end())return i->second.at(size_t(mz)*64+mx);}return coarse;}
std::vector<Cell> Terrain::fine_cells(int32_t x,int32_t z)const{(void)at(x,z);auto i=fine_patches.find(uint64_t(z)*width+x);if(profile!=2||i==fine_patches.end())return {};std::vector<Cell>v;v.reserve(4096);auto&p=i->second;if(p.index_bits==1&&p.palette.size()==2){for(int row=0;row<64;row++){auto word=p.row_bits(row);for(unsigned x=0;x<64;x++)v.push_back(p.palette[size_t((word>>x)&1)]);}}else for(size_t n=0;n<4096;n++)v.push_back(p.at(n));return v;}
std::array<uint16_t,64> Terrain::coverage_counts(int32_t x,int32_t z)const{auto&c=at(x,z);if(profile==2){auto p=fine_patches.find(uint64_t(z)*width+x);if(p!=fine_patches.end())return p->second.coverage_counts();}std::array<uint16_t,64>counts{};valid_cell(c);counts[size_t(c.kind)*8+c.theme]=4096;return counts;}
int32_t Terrain::height_for(TerrainKind k)const{if(size_t(k)>=8)throw Error("TERRAIN_KIND","index");return (profile==1?legacy_terrain_height_mm:terrain_height_mm)[size_t(k)];}
void Terrain::initialize_uniform(int32_t cw,int32_t ch,Cell c){valid_cell(c);if(cw<minimum_core_cells||ch<minimum_core_cells||cw>maximum_core_cells||ch>maximum_core_cells)throw Error("CREATION_DIMENSIONS","32..4096 management cells");profile=2;cell_mm=2000;guard=8;width=cw+16;height=ch+16;cells.clear();fine_patches.clear();rows.clear();rows.resize(size_t(height));for(int32_t z=0;z<height;z++){auto&r=rows[size_t(z)];if(z<guard||z>=height-guard||c==Cell{TerrainKind::DeepOcean,0,1})r.push_back({width,{TerrainKind::DeepOcean,0,1}});else r={{guard,{TerrainKind::DeepOcean,0,1}},{width-guard,c},{width,{TerrainKind::DeepOcean,0,1}}};}geometry_revision=1;}
void Terrain::set_cell(int32_t x,int32_t z,Cell c){valid_cell(c);(void)at(x,z);if(!editable(x,z)&&c.kind!=TerrainKind::DeepOcean)throw Error("TERRAIN_GUARD","immutable guard");if(profile==1){cells[size_t(z)*width+x]=c;return;}auto&r=rows[size_t(z)];std::vector<CellRun>next;next.reserve(r.size()+2);int32_t begin=0;auto append=[&](int32_t end,Cell v){if(end<=0)return;if(!next.empty()&&next.back().value==v)next.back().end_x=end;else next.push_back({end,v});};for(auto&run:r){if(x>=begin&&x<run.end_x){if(begin<x)append(x,run.value);append(x+1,c);if(x+1<run.end_x)append(run.end_x,run.value);}else append(run.end_x,run.value);begin=run.end_x;}r=std::move(next);fine_patches.erase(uint64_t(z)*width+x);}
void Terrain::set_fine_cells(int32_t x,int32_t z,std::span<const Cell>v){if(profile!=2||!editable(x,z))throw Error("TERRAIN_PATCH","editable profile2 cell required");auto p=FinePatch::pack(v);Cell center=v[32*64+32];set_cell(x,z,center);if(p.palette.size()>1)fine_patches.emplace(uint64_t(z)*width+x,std::move(p));}
uint64_t Terrain::storage_bytes()const{uint64_t n=sizeof(Terrain)+uint64_t(cells.capacity())*sizeof(Cell)+uint64_t(rows.capacity())*sizeof(std::vector<CellRun>);for(auto&r:rows)n+=uint64_t(r.capacity())*sizeof(CellRun);for(auto&[k,p]:fine_patches){(void)k;n+=128+uint64_t(p.palette.capacity())*sizeof(Cell)+p.indices.capacity();}return n;}
uint64_t Terrain::dry_micro_count()const{uint64_t n=0;if(profile==1){for(int32_t z=guard;z<height-guard;z++)for(int32_t x=guard;x<width-guard;x++)if(!terrain_is_water(at(x,z).kind))++n;return n;}for(int32_t z=guard;z<height-guard;z++){int32_t begin=0;for(auto&r:rows[size_t(z)]){auto lo=std::max(begin,guard),hi=std::min(r.end_x,width-guard);if(hi>lo&&!terrain_is_water(r.value.kind))n+=uint64_t(hi-lo)*4096;begin=r.end_x;}}for(auto&[key,p]:fine_patches){auto x=int32_t(key%uint64_t(width)),z=int32_t(key/uint64_t(width));if(!terrain_is_water(at(x,z).kind))n-=4096;if(p.index_bits==1&&p.palette.size()==2){uint64_t ones=0;for(int row=0;row<64;row++)ones+=uint64_t(std::popcount(p.row_bits(row)));if(!terrain_is_water(p.palette[0].kind))n+=4096-ones;if(!terrain_is_water(p.palette[1].kind))n+=ones;}else for(size_t i=0;i<4096;i++)if(!terrain_is_water(p.at(i).kind))++n;}return n;}
uint64_t Terrain::fill_water_only(int32_t x,int32_t z,TerrainKind k,uint8_t theme,uint64_t rev){if(profile!=2||!editable(x,z)||terrain_is_water(k)||theme>7||!rev||rev>uint64_t(INT64_MAX)||rev<=geometry_revision)throw Error("FILL_WATER_INPUT","profile2 editable dry kind, new revision");std::vector<Cell>v=fine_cells(x,z);if(v.empty())v.assign(4096,at(x,z));uint64_t changed=0;for(auto&c:v)if(terrain_is_water(c.kind)){c={k,theme,rev};++changed;}if(!changed)return 0;Terrain candidate=*this;candidate.set_fine_cells(x,z,v);candidate.geometry_revision=rev;candidate.validate();*this=std::move(candidate);return changed;}
std::optional<SurfacePoint> Terrain::support(int64_t x,int64_t z)const{if(x<0||z<0||x>INT64_MAX/1000||z>INT64_MAX/1000)return {};return support_um(x*1000,z*1000);}
std::optional<SurfacePoint> Terrain::support_um(int64_t x,int64_t z)const{require_query_geometry(*this);int64_t side=int64_t(cell_mm)*1000;if(x<0||z<0||x>=int64_t(width)*side||z>=int64_t(height)*side)return {};auto cx=int32_t(x/side),cz=int32_t(z/side);int d=micro_divisions();auto mx=int32_t((x%side)*d/side),mz=int32_t((z%side)*d/side);auto&c=sample_cell(cx,cz,mx,mz);return SurfacePoint{cx,cz,height_for(c.kind),c.kind,editable(cx,cz),terrain_is_water(c.kind),mx,mz,c.theme,terrain_is_water(c.kind)?-height_for(c.kind):0};}
void Terrain::validate()const{require_query_geometry(*this);if(!geometry_revision||geometry_revision>uint64_t(INT64_MAX)||guard!=8||width<48||height<48||storage_budget_bytes>terrain_geometry_budget_bytes||storage_budget_bytes<4096)throw Error("TERRAIN_PROFILE","dimensions/revision/budget");if(profile==1){if(width>1024||height>1024||!rows.empty()||!fine_patches.empty())throw Error("TERRAIN_PROFILE","legacy dense profile");for(int32_t z=0;z<height;z++)for(int32_t x=0;x<width;x++){auto&c=at(x,z);valid_cell(c);if(!editable(x,z)&&c.kind!=TerrainKind::DeepOcean)throw Error("TERRAIN_GUARD","deep ocean guard");}return;}if(!cells.empty()||storage_bytes()>storage_budget_bytes)throw Error("CREATION_BUDGET","sparse geometry resident bytes");uint64_t encoded_bound=1024+uint64_t(height)*16;for(auto&r:rows)encoded_bound+=uint64_t(r.size())*28+uint64_t((r.size()+2047)/2048)*4;
 // schema2 shares palettes. Each patch object is at most96 fixed ASCII bytes
 // (including ten-digit cell/palette IDs, codec/width and list punctuation)
 // plus its exact hex payload. Registry cells cost20 hex bytes each; array
 // punctuation/chunk strings are counted only once per unique palette.
 auto palette_less=[](const std::vector<Cell>*a,const std::vector<Cell>*b){return std::lexicographical_compare(a->begin(),a->end(),b->begin(),b->end(),cell_less);};std::set<const std::vector<Cell>*,decltype(palette_less)>palettes(palette_less);
 for(auto&[k,p]:fine_patches){(void)k;encoded_bound+=96+uint64_t(p.indices.size())*2;if(palettes.insert(&p.palette).second)encoded_bound+=4+uint64_t(p.palette.size())*20+uint64_t((p.palette.size()+2047)/2048)*4;}if(encoded_bound>133169152)throw Error("CREATION_BUDGET","terrain canonical save segment exceeds127MiB");for(int32_t z=0;z<height;z++){int32_t prev=0;const Cell*last=nullptr;for(auto&r:rows[size_t(z)]){valid_cell(r.value);if(r.value.revision>geometry_revision)throw Error("TERRAIN_PROFILE","cell revision exceeds geometry");if(r.end_x<=prev||r.end_x>width||(last&&*last==r.value))throw Error("TERRAIN_PROFILE","canonical RLE");if((z<guard||z>=height-guard||prev<guard||r.end_x>width-guard)&&r.value.kind!=TerrainKind::DeepOcean)throw Error("TERRAIN_GUARD","deep ocean guard");prev=r.end_x;last=&r.value;}if(prev!=width)throw Error("TERRAIN_PROFILE","row coverage");}for(auto&[key,p]:fine_patches){if(key>=uint64_t(width)*height)throw Error("TERRAIN_PATCH","key bounds");auto x=int32_t(key%width),z=int32_t(key/width);if(!editable(x,z))throw Error("TERRAIN_GUARD","no fine guard");p.validate();for(auto&c:p.palette)if(c.revision>geometry_revision)throw Error("TERRAIN_PATCH","cell revision exceeds geometry");if(p.at(32*64+32)!=at(x,z))throw Error("TERRAIN_PATCH","coarse representative is exact center");}}
Hash Terrain::surface_hash()const{
 Sha256Stream stream;auto put=[&](uint64_t v,unsigned n){std::array<uint8_t,8>b{};for(unsigned i=0;i<n;i++)b[i]=uint8_t(v>>(8*i));stream.update(std::span<const uint8_t>(b).first(n));};auto cell=[&](const Cell&c){put(uint8_t(c.kind),1);put(c.theme,1);put(c.revision,8);};
 if(profile==2){constexpr std::array<uint8_t,8>marker{'S','O','N','N','T','E','R','2'};stream.update(marker);put(profile,4);}put(geometry_revision,8);put(uint32_t(width),4);put(uint32_t(height),4);put(uint32_t(cell_mm),4);put(uint32_t(guard),4);
 if(profile==1){for(auto&c:cells)cell(c);}else{put(64,4);for(auto&r:rows){put(r.size(),4);for(auto&v:r){put(uint32_t(v.end_x),4);cell(v.value);}}put(fine_patches.size(),8);for(auto&[key,p]:fine_patches){put(key,8);put(p.palette.size(),4);put(p.index_bits,1);for(auto&c:p.palette)cell(c);if(!p.encoding)stream.update(p.indices);else{auto raw=p.canonical_indices();stream.update(raw);}}}return stream.finish();
}
namespace {
Mesh make_mesh(const Terrain&t,int32_t sx,int32_t sz,int32_t nx,int32_t nz,bool coarse){range(t,sx,sz,nx,nz);Mesh m;const double cm=t.cell_mm/1000.0,ms=cm/t.micro_divisions();using Key=std::tuple<int32_t,int32_t,uint8_t,uint8_t>;std::map<Key,std::pair<int32_t,Cell>>active;
 auto flush=[&](const Key&k,const std::pair<int32_t,Cell>&v,int32_t endz){top(m,t,std::get<0>(k)*cm,v.first*cm,std::get<1>(k)*cm,endz*cm,v.second);};
 for(int32_t z=sz;z<sz+nz;z++){std::map<Key,std::pair<int32_t,Cell>>next;for(int32_t x=sx;x<sx+nx;){if(!coarse&&t.has_fine_patch(x,z)){++x;continue;}const Cell c=t.at(x,z);int32_t end=x+1;while(end<sx+nx&&(coarse||!t.has_fine_patch(end,z))&&visible_same(c,t.at(end,z)))++end;Key key{x,end,uint8_t(c.kind),c.theme};auto old=active.find(key);next.emplace(key,old==active.end()?std::pair{z,c}:old->second);x=end;}for(auto&[k,v]:active)if(!next.contains(k))flush(k,v,z);active=std::move(next);}for(auto&[k,v]:active)flush(k,v,sz+nz);
 if(!coarse&&t.profile==2){for(auto it=t.fine_patches.lower_bound(uint64_t(sz)*t.width);it!=t.fine_patches.end()&&it->first<uint64_t(sz+nz)*t.width;++it){int32_t x=int32_t(it->first%t.width),z=int32_t(it->first/t.width);if(x<sx||x>=sx+nx)continue;std::array<bool,4096>used{};for(int mz=0;mz<64;mz++)for(int mx=0;mx<64;mx++){size_t index=size_t(mz)*64+mx;if(used[index])continue;auto&c=it->second.at(index);int ex=mx+1;while(ex<64&&!used[size_t(mz)*64+ex]&&visible_same(c,it->second.at(size_t(mz)*64+ex)))++ex;int ez=mz+1;for(;ez<64;ez++){bool ok=true;for(int a=mx;a<ex;a++)if(used[size_t(ez)*64+a]||!visible_same(c,it->second.at(size_t(ez)*64+a))){ok=false;break;}if(!ok)break;}for(int b=mz;b<ez;b++)for(int a=mx;a<ex;a++)used[size_t(b)*64+a]=true;top(m,t,x*cm+mx*ms,z*cm+mz*ms,x*cm+ex*ms,z*cm+ez*ms,c);}}}
 auto micro=[&](int64_t gx,int64_t gz)->Cell{int d=coarse?1:t.micro_divisions();if(gx<0||gz<0||gx>=int64_t(t.width)*d||gz>=int64_t(t.height)*d)return {TerrainKind::DeepOcean,0,1};return coarse?t.at(int32_t(gx),int32_t(gz)):t.sample_cell(int32_t(gx/d),int32_t(gz/d),int32_t(gx%d),int32_t(gz%d));};
 auto side=[&](int dir,double edge,double a,double b,double hi,double lo,const Cell&c){if(dir==0)quad(m,{Vec3{edge,hi,b},Vec3{edge,hi,a},Vec3{edge,lo,a},Vec3{edge,lo,b}},{-1,0,0},c);if(dir==1)quad(m,{Vec3{edge,hi,a},Vec3{edge,hi,b},Vec3{edge,lo,b},Vec3{edge,lo,a}},{1,0,0},c);if(dir==2)quad(m,{Vec3{a,hi,edge},Vec3{b,hi,edge},Vec3{b,lo,edge},Vec3{a,lo,edge}},{0,0,-1},c);if(dir==3)quad(m,{Vec3{b,hi,edge},Vec3{a,hi,edge},Vec3{a,lo,edge},Vec3{b,lo,edge}},{0,0,1},c);};
 const int d=coarse?1:t.micro_divisions();const double step=cm/d;
 for(int32_t z=sz;z<sz+nz;z++)for(int32_t x=sx;x<sx+nx;x++){bool fine=!coarse&&t.has_fine_patch(x,z);for(int dir=0;dir<4;dir++){int lines=fine?d:1;int neighbour_x=x+(dir==0?-1:dir==1?1:0),neighbour_z=z+(dir==2?-1:dir==3?1:0);bool edge_fine=!coarse&&neighbour_x>=0&&neighbour_z>=0&&neighbour_x<t.width&&neighbour_z<t.height&&t.has_fine_patch(neighbour_x,neighbour_z);int samples=(fine||edge_fine)?d:1;for(int line=0;line<lines;line++){for(int a=0;a<samples;){int mx=dir<2?(fine?line:(dir==0?0:d-1)):(samples==1?0:a),mz=dir<2?(samples==1?0:a):(fine?line:(dir==2?0:d-1));int64_t gx=int64_t(x)*d+mx,gz=int64_t(z)*d+mz;Cell c=micro(gx,gz);auto neighbor=micro(gx+(dir==0?-1:dir==1?1:0),gz+(dir==2?-1:dir==3?1:0));if(!fine){int64_t ng=dir<2?int64_t(neighbour_x)*d+(dir==0?d-1:0):gx, nzg=dir>=2?int64_t(neighbour_z)*d+(dir==2?d-1:0):gz;neighbor=micro(ng,nzg);}auto hi=t.height_for(c.kind),lo=t.height_for(neighbor.kind);int end=a+1;while(end<samples){int ex=dir<2?mx:end,ez=dir<2?end:mz;auto cc=micro(int64_t(x)*d+ex,int64_t(z)*d+ez);int64_t ng=dir<2?(fine?int64_t(x)*d+ex+(dir==0?-1:1):int64_t(neighbour_x)*d+(dir==0?d-1:0)):int64_t(x)*d+ex;int64_t nzg=dir>=2?(fine?int64_t(z)*d+ez+(dir==2?-1:1):int64_t(neighbour_z)*d+(dir==2?d-1:0)):int64_t(z)*d+ez;auto nn=micro(ng,nzg);if(!visible_same(cc,c)||t.height_for(nn.kind)!=lo)break;++end;}if(hi>lo){double edge=dir<2?x*cm+(fine?(mx+(dir==1))*step:(dir==1?cm:0)):z*cm+(fine?(mz+(dir==3))*step:(dir==3?cm:0));double start=(dir<2?z:x)*cm+(samples==1?0:a*step),finish=(dir<2?z:x)*cm+(samples==1?cm:end*step);side(dir,edge,start,finish,hi/1000.0,lo/1000.0,c);}a=end;}}}}
 return m;}
}
Mesh Terrain::mesh(int32_t sx,int32_t sz,int32_t nx,int32_t nz)const{return make_mesh(*this,sx,sz,nx,nz,false);}
Mesh Terrain::mesh_coarse(int32_t sx,int32_t sz,int32_t nx,int32_t nz)const{return make_mesh(*this,sx,sz,nx,nz,true);}
std::optional<RayHit> Terrain::raycast(Vec3 o,Vec3 d,double max)const{require_query_geometry(*this);if(!std::isfinite(o.x)||!std::isfinite(o.y)||!std::isfinite(o.z)||!std::isfinite(d.x)||!std::isfinite(d.y)||!std::isfinite(d.z)||!std::isfinite(max)||max<=0)throw Error("INVALID_RAY","finite coordinates");double scale=std::max({std::abs(d.x),std::abs(d.y),std::abs(d.z)});if(scale==0)throw Error("INVALID_RAY","zero direction");d.x/=scale;d.y/=scale;d.z/=scale;double len=std::hypot(d.x,d.y,d.z);d.x/=len;d.y/=len;d.z/=len;double cm=cell_mm/1000.0,begin=0,end=max;auto slab=[&](double p,double v,double size){if(std::abs(v)<1e-15)return p>=0&&p<size;double a=-p/v,b=(size-p)/v;if(a>b)std::swap(a,b);begin=std::max(begin,a);end=std::min(end,b);return begin<=end;};if(!slab(o.x,d.x,width*cm)||!slab(o.z,d.z,height*cm)||end<0)return {};begin=std::max(begin,0.0);double t=begin;auto query=[&](double x,double z)->std::optional<SurfacePoint>{if(x<0||z<0||x>=width*cm||z>=height*cm)return {};return support_um(int64_t(std::floor(x*1000000)),int64_t(std::floor(z*1000000)));};for(int64_t n=0;n<int64_t(width+height)*64+8&&t<=end+1e-9;n++){double px=o.x+d.x*(t+1e-9),pz=o.z+d.z*(t+1e-9);px=std::clamp(px,0.0,std::nextafter(width*cm,0.0));pz=std::clamp(pz,0.0,std::nextafter(height*cm,0.0));auto p=query(px,pz);if(!p)break;bool fine=has_fine_patch(p->cell_x,p->cell_z);double step=fine?cm/64:cm,x0=p->cell_x*cm+(fine?p->micro_x*step:0),z0=p->cell_z*cm+(fine?p->micro_z*step:0),x1=x0+step,z1=z0+step;double tx=std::abs(d.x)<1e-15?INFINITY:((d.x>0?x1:x0)-o.x)/d.x,tz=std::abs(d.z)<1e-15?INFINITY:((d.z>0?z1:z0)-o.z)/d.z,exit=std::min({tx,tz,end});double best=INFINITY;Vec3 normal;auto test=[&](double hit,Vec3 norm,double lo,bool side){if(hit<t-1e-8||hit>exit+1e-8||hit<0||hit>max)return;double x=o.x+d.x*hit,y=o.y+d.y*hit,z=o.z+d.z*hit;if(x<x0-1e-8||x>x1+1e-8||z<z0-1e-8||z>z1+1e-8||(side&&(y<lo-1e-8||y>p->height_mm/1000.0+1e-8)))return;if(hit<best){best=hit;normal=norm;}};double hi=p->height_mm/1000.0;if(std::abs(d.y)>1e-15)test((hi-o.y)/d.y,{0,1,0},0,false);for(int dir=0;dir<4;dir++){double v=dir<2?d.x:d.z;if(std::abs(v)<1e-15)continue;double edge=dir==0?x0:dir==1?x1:dir==2?z0:z1,hit=(edge-(dir<2?o.x:o.z))/v;double x=o.x+d.x*hit,z=o.z+d.z*hit;auto q=query(dir==0?edge-1e-7:dir==1?edge+1e-7:x,dir==2?edge-1e-7:dir==3?edge+1e-7:z);double lo=q?q->height_mm/1000.0:-20;if(hi>lo)test(hit,dir==0?Vec3{-1,0,0}:dir==1?Vec3{1,0,0}:dir==2?Vec3{0,0,-1}:Vec3{0,0,1},lo,true);}if(std::isfinite(best))return RayHit{best,{o.x+d.x*best,o.y+d.y*best,o.z+d.z*best},normal,p->cell_x,p->cell_z,p->kind,p->micro_x,p->micro_z,p->theme,p->wet};if(exit>=end)break;if(exit<t-1e-8)throw Error("INVALID_RAY","DDA progress");t=exit;}
 return {};}
} // sonn
