#include "sonnheide.hpp"
#include <algorithm>
#include <limits>
namespace sonn {
namespace {
constexpr std::array<std::string_view,11> phases{"FREEZE","INTEGRATE_OLD","MARK_DUE_DEATH","APPLY_BOUNDARY_COMMANDS","DELIVER_AND_FREEZE_DUE","PREPARE_PHYSICAL","RESOLVE_PHYSICAL","ACTUAL_INTERACTIONS","DUE_EXECUTION","FINAL_LIFECYCLE","PUBLISH"};
uint64_t next(uint64_t x){if(x>=uint64_t(INT64_MAX))throw Error("INTEGER_OVERFLOW","authority counter");return x+1;}
void name_valid(const std::string& s){(void)canonical_json(Json(s));size_t count=0;for(unsigned char c:s){if(c<32||c==127)throw Error("INVALID_NAME","control character");if((c&0xc0)!=0x80)++count;}if(count<1||count>128)throw Error("INVALID_NAME","1..128 Unicode code points");}
Json command_payload(const Command&c){switch(c.kind){case Command::Kind::RenameWorld:return Json::Object{{"kind","RenameWorld"},{"name",c.text}};case Command::Kind::SetAge:return Json::Object{{"kind","SetEnvironmentAge"},{"age",c.age==Age::Light?"light":"darkness"}};case Command::Kind::SetAgeAutomatic:return Json::Object{{"kind","SetAgeAutomatic"},{"enabled",c.boolean},{"light_duration_tick",int64_t(c.light_duration_tick)},{"dark_duration_tick",int64_t(c.dark_duration_tick)}};case Command::Kind::SetRule:return Json::Object{{"kind","SetWorldRule"},{"rule",c.text},{"value",c.boolean}};}throw Error("UNSUPPORTED_COMMAND","kind");}
void apply(World&w,const Command&c){switch(c.kind){case Command::Kind::RenameWorld:name_valid(c.text);w.name=c.text;break;case Command::Kind::SetAge:if(c.age!=Age::Light&&c.age!=Age::Darkness)throw Error("INVALID_AGE","enum");w.age.current=c.age;w.age.automatic=false;w.age.remaining_tick=0;break;case Command::Kind::SetAgeAutomatic:if(!c.light_duration_tick||!c.dark_duration_tick||c.light_duration_tick>uint64_t(INT64_MAX)||c.dark_duration_tick>uint64_t(INT64_MAX))throw Error("INVALID_AGE_DURATION","positive int64 ticks");w.age.automatic=c.boolean;w.age.light_duration_tick=c.light_duration_tick;w.age.dark_duration_tick=c.dark_duration_tick;w.age.remaining_tick=c.boolean?(w.age.current==Age::Light?c.light_duration_tick:c.dark_duration_tick):0;break;case Command::Kind::SetRule:{auto i=w.rules.find(c.text);if(i==w.rules.end())throw Error("UNSUPPORTED_RULE",c.text);i->second=c.boolean;break;}}}
Json consequence(const World&w,const Command&c){World trial=w;apply(trial,c);return Json::Object{{"before",w.query()},{"after",trial.query()},{"command",command_payload(c)},{"elapsed_tick",0},{"population_change",0},{"inventory_change",0}};}
}
Ref World::ref()const{return {id,"world",1,1};}
Json World::query()const{Json::Object r;for(auto&[k,v]:rules)r.emplace(k,v);return Json::Object{{"ref",ref_json(ref())},{"revision",std::to_string(revision)},{"tick",std::to_string(tick)},{"boundary_ordinal",std::to_string(boundary_ordinal)},{"name",name},{"age",age.current==Age::Light?"light":"darkness"},{"age_automatic",age.automatic},{"age_remaining_tick",std::to_string(age.remaining_tick)},{"world_rules",r},{"population",std::to_string(population)},{"awakened_animals",std::to_string(awakened_animals)},{"buildings",std::to_string(buildings)},{"width_cells",terrain.width},{"height_cells",terrain.height},{"cell_mm",terrain.cell_mm},{"surface_hash",hex(terrain.surface_hash())},{"definition_hash",hex(definition_hash)},{"asset_hash",hex(asset_hash)},{"implemented_stage","S00_S01"}};}
Hash World::deterministic_hash()const{return sha256(encode_save(*this));}
void World::validate(const Hash&expected)const{if(std::all_of(asset_hash.begin(),asset_hash.end(),[](auto b){return b==0;}))throw Error("ASSET_MISSING","admitted assets required");if(definition_hash!=expected)throw Error("DEFINITION_MISSING","exact definition package required");name_valid(name);terrain.validate();if(std::all_of(id.begin(),id.end(),[](auto b){return b==0;}))throw Error("INVALID_WORLD_ID","nil identity");if(tick>uint64_t(INT64_MAX)||revision==0||revision>uint64_t(INT64_MAX)||boundary_ordinal>uint64_t(INT64_MAX)||input_sequence>uint64_t(INT64_MAX))throw Error("INTEGER_OVERFLOW","clock/revision");if(age.current!=Age::Light&&age.current!=Age::Darkness)throw Error("INVALID_AGE","enum");if(!age.light_duration_tick||!age.dark_duration_tick||age.light_duration_tick>uint64_t(INT64_MAX)||age.dark_duration_tick>uint64_t(INT64_MAX)||age.remaining_tick>uint64_t(INT64_MAX)||(!age.automatic&&age.remaining_tick)||(age.automatic&&(!age.remaining_tick||age.remaining_tick>(age.current==Age::Light?age.light_duration_tick:age.dark_duration_tick))))throw Error("INVALID_AGE","remaining/duration");if(population||awakened_animals||buildings)throw Error("UNSUPPORTED_DOMAIN","S01 world has zero life/buildings");if(rules.size()!=3||!rules.contains("aging")||!rules.contains("hunger_consequences")||!rules.contains("thermal_consequences"))throw Error("UNSUPPORTED_RULE","S01 rule set");std::map<std::string,Hash>seen;for(auto&r:receipts){if(r.command_id.empty()||r.command_id.size()>128||!r.committed_revision||r.committed_revision>revision||!seen.emplace(r.command_id,r.payload_hash).second||r.payload_hash!=sha256(canonical_json(r.effects.at("command")))||parse_ref(r.effects.at("before").at("ref"))!=ref()||parse_ref(r.effects.at("after").at("ref"))!=ref()||r.effects.at("elapsed_tick").integer()!=0||r.effects.at("population_change").integer()!=0||r.effects.at("inventory_change").integer()!=0)throw Error("INVALID_RECEIPT","unique command/revision");}if(receipts.size()>1000000)throw Error("SAVE_LIMIT","receipts");(void)canonical_json(provenance);if(provenance.at("original_source_read_only").boolean()!=true||provenance.at("core_width").integer()!=terrain.width-16||provenance.at("core_height").integer()!=terrain.height-16||provenance.at("soil_theme").integer()<0||provenance.at("soil_theme").integer()>7||provenance.at("surface_sha256").string()!=hex(terrain.surface_hash()))throw Error("SAVE_PROVENANCE","S01 immutable creation surface");}
World create_candidate(const CreationDraft&d,const DefinitionPackage&defs,const Geography*geo,const std::function<bool()>&cancel){if(cancel&&cancel())throw Error("CREATION_CANCELED","before allocation");if(!d.session_generation||!d.draft_generation||!d.candidate_generation)throw Error("STALE_GENERATION","zero");if(d.soil_theme>7)throw Error("INVALID_SOIL_THEME","0..7");if(d.core_width<32||d.core_width>1008)throw Error("CREATION_DIMENSIONS","core width 32..1008");int32_t ch=d.core_height;Json::Object source{{"creation_kind",d.kind==CreationKind::Earth?"earth":d.kind==CreationKind::BlankLand?"blank_land":"blank_sea"},{"original_source_read_only",true}};std::vector<uint8_t>land;
 if(d.kind==CreationKind::Earth){if(!geo)throw Error("GEO_SOURCE_MISSING","official full source required");auto&r=d.selection;int64_t span=int64_t(r.east_unwrapped_udeg)-r.west_udeg,lat=int64_t(r.north_udeg)-r.south_udeg;if(r.west_udeg< -180000000||r.west_udeg>=180000000||span<=0||span>60000000||lat<=0||lat>60000000||r.south_udeg< -80000000||r.north_udeg>80000000)throw Error("EARTH_SELECTION","60 degree / +/-80 degree bounds");ch=int32_t((int64_t(d.core_width)*lat+span-1)/span);if(ch<32||ch>1008)throw Error("CREATION_DIMENSIONS","derived height 32..1008");source.emplace("source_sha256",hex(geo->source_hash()));source.emplace("source_version","GSHHG_2.3.7");source.emplace("projection","equirectangular_standard_parallel_0");source.emplace("west_udeg",r.west_udeg);source.emplace("east_unwrapped_udeg",r.east_unwrapped_udeg);source.emplace("south_udeg",r.south_udeg);source.emplace("north_udeg",r.north_udeg);
 }else if(d.kind!=CreationKind::BlankSea&&d.kind!=CreationKind::BlankLand)throw Error("CREATION_KIND","enum");
 if(ch<32||ch>1008)throw Error("CREATION_DIMENSIONS","core height");uint64_t count=uint64_t(d.core_width+16)*uint64_t(ch+16);if(count>1048576||count*uint64_t(sizeof(Cell)+6)>d.budget_bytes||d.budget_bytes>268435456)throw Error("CREATION_BUDGET","terrain candidate allocation");if(d.kind==CreationKind::Earth)land=geo->sample_world_selection(d.selection,d.core_width,ch,cancel);
 World w;w.id=d.world_id;w.seed=d.seed;w.definition_hash=defs.hash;w.asset_hash=defs.asset_hash;w.name=d.name;w.terrain.width=d.core_width+16;w.terrain.height=ch+16;w.terrain.cells.resize(size_t(count),Cell{TerrainKind::DeepOcean,0,1});for(int32_t z=0;z<ch;z++){if(cancel&&cancel())throw Error("CREATION_CANCELED","row");for(int32_t x=0;x<d.core_width;x++){bool soil=d.kind==CreationKind::BlankLand||(d.kind==CreationKind::Earth&&land[size_t(z)*size_t(d.core_width)+size_t(x)]);auto&cell=w.terrain.cells[size_t(z+8)*size_t(w.terrain.width)+size_t(x+8)];cell.kind=soil?TerrainKind::Soil:TerrainKind::CloseOcean;cell.theme=soil?d.soil_theme:0;}}w.rules={{"aging",true},{"hunger_consequences",true},{"thermal_consequences",true}};source.emplace("soil_theme",int(d.soil_theme));source.emplace("core_width",d.core_width);source.emplace("core_height",ch);source.emplace("initial_population",0);source.emplace("initial_awakened_animals",0);source.emplace("initial_buildings",0);source.emplace("surface_sha256",hex(w.terrain.surface_hash()));w.provenance=source;w.validate(defs.hash);return w;}
Authority::Authority(World w,uint64_t session):world_(std::move(w)),session_(session),writer_(std::this_thread::get_id()){if(!session_)throw Error("STALE_GENERATION","session");world_.validate(world_.definition_hash);}
void Authority::check_writer()const{if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","owner thread required");}
PreparedCommand Authority::prepare(const Envelope&e,const Command&c)const{check_writer();if(e.world_id!=world_.id||e.session_generation!=session_)throw Error("STALE_GENERATION","world/session");if(e.command_id.empty()||e.command_id.size()>128)throw Error("COMMAND_ID","1..128bytes");auto p=command_payload(c);auto hash=sha256(canonical_json(p));auto i=std::find_if(world_.receipts.begin(),world_.receipts.end(),[&](auto&r){return r.command_id==e.command_id;});if(i!=world_.receipts.end()){if(i->payload_hash!=hash)throw Error("IDEMPOTENCY_CONFLICT",e.command_id);return {e,c,sha256(canonical_json(i->effects)),i->effects};}if(e.expected_revision!=world_.revision)throw Error("STALE_REVISION","reprepare and preview");if(e.input_sequence<=world_.input_sequence||e.input_sequence>uint64_t(INT64_MAX))throw Error("INPUT_SEQUENCE","trusted monotonic input");auto preview=consequence(world_,c);return {e,c,sha256(canonical_json(preview)),std::move(preview)};}
CommandReceipt Authority::commit(const PreparedCommand&p){check_writer();auto hash=sha256(canonical_json(command_payload(p.command)));for(auto&r:world_.receipts)if(r.command_id==p.envelope.command_id){if(r.payload_hash!=hash||p.envelope.world_id!=world_.id||p.envelope.session_generation!=session_)throw Error("IDEMPOTENCY_CONFLICT",r.command_id);return r;}auto again=prepare(p.envelope,p.command);if(again.consequence_hash!=p.consequence_hash||again.preview!=p.preview)throw Error("PREVIEW_CHANGED","reprepare required");World candidate=world_;apply(candidate,p.command);candidate.boundary_ordinal=next(candidate.boundary_ordinal);candidate.input_sequence=p.envelope.input_sequence;candidate.revision=next(candidate.revision);CommandReceipt receipt{p.envelope.command_id,hash,candidate.revision,p.preview};candidate.receipts.push_back(receipt);candidate.validate(candidate.definition_hash);world_=std::move(candidate);return receipt;}
TickTrace Authority::advance_tick(){check_writer();uint64_t tick=next(world_.tick),revision=next(world_.revision);AgeState age=world_.age;
 // No life, pending commands, messages, motion or economy participants exist in S01.
 // Each stage completes before the following barrier; only the last stage publishes authority.
 for(size_t phase=0;phase<phases.size();++phase){switch(phase){
 case 8: // DUE_EXECUTION: actual Age deadline has one owner and advances exactly once.
  if(age.automatic&&--age.remaining_tick==0){age.current=age.current==Age::Light?Age::Darkness:Age::Light;age.remaining_tick=age.current==Age::Light?age.light_duration_tick:age.dark_duration_tick;}break;
 case 10:world_.tick=tick;world_.revision=revision;world_.age=age;break;
 default:break; // Explicit empty-domain barrier, not a claim that future systems are implemented.
 }}return {tick,revision,phases};}
WorldSession::WorldSession():writer_(std::this_thread::get_id()){}
CreationDraft WorldSession::begin(CreationDraft d){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");draft_generation_=next(draft_generation_);candidate_generation_=next(candidate_generation_);d.session_generation=generation_;d.draft_generation=draft_generation_;d.candidate_generation=candidate_generation_;draft_=d;return d;}
void WorldSession::cancel(){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");draft_generation_=next(draft_generation_);candidate_generation_=next(candidate_generation_);draft_.reset();}
bool WorldSession::accepts(const CreationDraft&d)const{return draft_&&d.session_generation==generation_&&d.draft_generation==draft_generation_&&d.candidate_generation==candidate_generation_&&d.world_id==draft_->world_id&&d.kind==draft_->kind&&d.name==draft_->name&&d.core_width==draft_->core_width&&d.core_height==draft_->core_height&&d.soil_theme==draft_->soil_theme&&d.budget_bytes==draft_->budget_bytes&&d.seed==draft_->seed&&d.selection.west_udeg==draft_->selection.west_udeg&&d.selection.east_unwrapped_udeg==draft_->selection.east_unwrapped_udeg&&d.selection.south_udeg==draft_->selection.south_udeg&&d.selection.north_udeg==draft_->selection.north_udeg;}
bool WorldSession::publish(const CreationDraft&d,World c,SaveStore&store,const DefinitionPackage&defs,Checkpoint&result,SaveFault fault){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");if(!accepts(d)||c.id!=d.world_id){result={SaveStatus::Failed,"STALE_GENERATION"};return false;}c.validate(defs.hash);uint64_t g=next(generation_);auto ready=std::make_unique<Authority>(c,g);result=store.save(c,defs,fault);if(result.status!=SaveStatus::Committed)return false;generation_=g;active_=std::move(ready);draft_.reset();return true;}
void WorldSession::load_continue(SaveStore&s,const DefinitionPackage&d){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");auto c=s.continue_world(d);if(!c)throw Error("NO_CONTINUE","no checkpoint");uint64_t g=next(generation_);auto a=std::make_unique<Authority>(std::move(*c),g);generation_=g;draft_.reset();active_=std::move(a);}
void WorldSession::return_to_menu(){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");generation_=next(generation_);draft_.reset();active_.reset();}
} // sonn
