#include "sonnheide.hpp"
#include <algorithm>
#include <limits>
namespace sonn {
namespace {
constexpr std::array<std::string_view,11> phases{"FREEZE","INTEGRATE_OLD","MARK_DUE_DEATH","APPLY_BOUNDARY_COMMANDS","DELIVER_AND_FREEZE_DUE","PREPARE_PHYSICAL","RESOLVE_PHYSICAL","ACTUAL_INTERACTIONS","DUE_EXECUTION","FINAL_LIFECYCLE","PUBLISH"};
uint64_t next(uint64_t x){if(x>=uint64_t(INT64_MAX))throw Error("INTEGER_OVERFLOW","authority counter");return x+1;}
void name_valid(const std::string& s){(void)canonical_json(Json(s));size_t count=0;for(unsigned char c:s){if(c<32||c==127)throw Error("INVALID_NAME","control character");if((c&0xc0)!=0x80)++count;}if(count<1||count>128)throw Error("INVALID_NAME","1..128 Unicode code points");}
Json command_payload(const Command&c){switch(c.kind){case Command::Kind::RenameWorld:return Json::Object{{"kind","RenameWorld"},{"name",c.text}};case Command::Kind::SetAge:return Json::Object{{"kind","SetEnvironmentAge"},{"age",c.age==Age::Light?"light":"darkness"}};case Command::Kind::SetAgeAutomatic:return Json::Object{{"kind","SetAgeAutomatic"},{"enabled",c.boolean},{"light_duration_tick",int64_t(c.light_duration_tick)},{"dark_duration_tick",int64_t(c.dark_duration_tick)}};case Command::Kind::SetRule:return Json::Object{{"kind","SetWorldRule"},{"rule",c.text},{"value",c.boolean}};case Command::Kind::FillWaterOnly:return Json::Object{{"kind","FillWaterOnly"},{"cell_x",c.cell_x},{"cell_z",c.cell_z},{"land_kind",std::string(terrain_name(c.land_kind))},{"soil_theme",int(c.soil_theme)}};}throw Error("UNSUPPORTED_COMMAND","kind");}
void apply(World&w,const Command&c){switch(c.kind){case Command::Kind::RenameWorld:name_valid(c.text);w.name=c.text;break;case Command::Kind::SetAge:if(c.age!=Age::Light&&c.age!=Age::Darkness)throw Error("INVALID_AGE","enum");w.age.current=c.age;w.age.automatic=false;w.age.remaining_tick=0;break;case Command::Kind::SetAgeAutomatic:if(!c.light_duration_tick||!c.dark_duration_tick||c.light_duration_tick>uint64_t(INT64_MAX)||c.dark_duration_tick>uint64_t(INT64_MAX))throw Error("INVALID_AGE_DURATION","positive int64 ticks");w.age.automatic=c.boolean;w.age.light_duration_tick=c.light_duration_tick;w.age.dark_duration_tick=c.dark_duration_tick;w.age.remaining_tick=c.boolean?(w.age.current==Age::Light?c.light_duration_tick:c.dark_duration_tick):0;break;case Command::Kind::SetRule:{auto i=w.rules.find(c.text);if(i==w.rules.end())throw Error("UNSUPPORTED_RULE",c.text);i->second=c.boolean;break;}case Command::Kind::FillWaterOnly:w.terrain.fill_water_only(c.cell_x,c.cell_z,c.land_kind,c.soil_theme,next(w.terrain.geometry_revision));break;}}
Json consequence(const World&w,const Command&c){World trial=w;apply(trial,c);Json::Object result{{"before",w.query()},{"after",trial.query()},{"command",command_payload(c)},{"elapsed_tick",0},{"population_change",0},{"inventory_change",0}};if(c.kind==Command::Kind::FillWaterOnly)result.emplace("reclaimed_micro_cells",int64_t(trial.terrain.dry_micro_count()-w.terrain.dry_micro_count()));return result;}
void validate_creation_scale(const World& w){
 const auto& p=w.provenance.object();
 if(w.terrain.profile==2&&(w.provenance.at("terrain_profile").integer()!=2||w.provenance.at("surface_micro_um").integer()!=31250||w.provenance.at("micro_divisions").integer()!=64))throw Error("SAVE_PROVENANCE","frozen micro profile");
 constexpr std::array<std::string_view,5> fields{"terrain_cell_mm","core_physical_width_mm","core_physical_height_mm","domain_physical_width_mm","domain_physical_height_mm"};
 const bool has_scale=std::any_of(fields.begin(),fields.end(),[&](auto key){return p.contains(key);});
 // Older 2m S01 records have no scale metadata. Their saved cell_mm remains authoritative.
 if(!has_scale&&w.terrain.profile==1&&w.terrain.cell_mm==legacy_terrain_cell_size_mm)return;
 const std::array<int64_t,5> expected{w.terrain.cell_mm,int64_t(w.terrain.width-2*w.terrain.guard)*w.terrain.cell_mm,int64_t(w.terrain.height-2*w.terrain.guard)*w.terrain.cell_mm,int64_t(w.terrain.width)*w.terrain.cell_mm,int64_t(w.terrain.height)*w.terrain.cell_mm};
 for(size_t i=0;i<fields.size();++i)if(w.provenance.at(fields[i]).integer()!=expected[i])throw Error("SAVE_PROVENANCE","frozen physical scale");
 if(w.provenance.at("creation_kind").string()=="earth"){
  const int64_t west=w.provenance.at("west_udeg").integer(),east=w.provenance.at("east_unwrapped_udeg").integer(),south=w.provenance.at("south_udeg").integer(),north=w.provenance.at("north_udeg").integer();
  // Bounds precede subtraction, so malformed signed64 source metadata cannot overflow.
  if(west< -180000000||west>=180000000||east<=west||east>west+360000000||south< -90000000||south>=90000000||north<=south||north>90000000)throw Error("SAVE_PROVENANCE","frozen source selection bounds");
  const int64_t span=east-west,lat=north-south,core_width=w.terrain.width-2*w.terrain.guard;
  if((core_width*lat+span-1)/span!=w.terrain.height-2*w.terrain.guard||w.provenance.at("geographic_scale_mode").string()!="stylized_uniform_not_1_to_1"||w.provenance.at("game_mm_per_source_microdegree_numerator").integer()!=expected[1]||w.provenance.at("game_mm_per_source_microdegree_denominator").integer()!=span)throw Error("SAVE_PROVENANCE","frozen stylized geographic scale");
 }
}
}
Ref World::ref()const{return {id,"world",1,1};}
Json World::query()const{Json::Object r;for(auto&[k,v]:rules)r.emplace(k,v);return Json::Object{{"ref",ref_json(ref())},{"revision",std::to_string(revision)},{"tick",std::to_string(tick)},{"boundary_ordinal",std::to_string(boundary_ordinal)},{"name",name},{"age",age.current==Age::Light?"light":"darkness"},{"age_automatic",age.automatic},{"age_remaining_tick",std::to_string(age.remaining_tick)},{"world_rules",r},{"population",std::to_string(population)},{"awakened_animals",std::to_string(awakened_animals)},{"buildings",std::to_string(buildings)},{"width_cells",terrain.width},{"height_cells",terrain.height},{"cell_mm",terrain.cell_mm},{"terrain_profile",int(terrain.profile)},{"surface_micro_um",terrain.profile==2?terrain_micro_size_um:terrain.cell_mm*1000},{"dry_micro_cells",std::to_string(terrain.dry_micro_count())},{"total_micro_cells",std::to_string(uint64_t(terrain.width-2*terrain.guard)*uint64_t(terrain.height-2*terrain.guard)*uint64_t(terrain.micro_divisions())*uint64_t(terrain.micro_divisions()))},{"core_physical_width_mm",int64_t(terrain.width-2*terrain.guard)*terrain.cell_mm},{"core_physical_height_mm",int64_t(terrain.height-2*terrain.guard)*terrain.cell_mm},{"domain_physical_width_mm",int64_t(terrain.width)*terrain.cell_mm},{"domain_physical_height_mm",int64_t(terrain.height)*terrain.cell_mm},{"surface_hash",hex(terrain.surface_hash())},{"definition_hash",hex(definition_hash)},{"asset_hash",hex(asset_hash)},{"implemented_stage","S00_S01"}};}
Hash World::deterministic_hash()const{return sha256(encode_save(*this));}
void World::validate(const Hash&expected)const{if(std::all_of(asset_hash.begin(),asset_hash.end(),[](auto b){return b==0;}))throw Error("ASSET_MISSING","admitted assets required");if(definition_hash!=expected)throw Error("DEFINITION_MISSING","exact definition package required");name_valid(name);terrain.validate();if(std::all_of(id.begin(),id.end(),[](auto b){return b==0;}))throw Error("INVALID_WORLD_ID","nil identity");if(tick>uint64_t(INT64_MAX)||revision==0||revision>uint64_t(INT64_MAX)||boundary_ordinal>uint64_t(INT64_MAX)||input_sequence>uint64_t(INT64_MAX))throw Error("INTEGER_OVERFLOW","clock/revision");if(age.current!=Age::Light&&age.current!=Age::Darkness)throw Error("INVALID_AGE","enum");if(!age.light_duration_tick||!age.dark_duration_tick||age.light_duration_tick>uint64_t(INT64_MAX)||age.dark_duration_tick>uint64_t(INT64_MAX)||age.remaining_tick>uint64_t(INT64_MAX)||(!age.automatic&&age.remaining_tick)||(age.automatic&&(!age.remaining_tick||age.remaining_tick>(age.current==Age::Light?age.light_duration_tick:age.dark_duration_tick))))throw Error("INVALID_AGE","remaining/duration");if(population||awakened_animals||buildings)throw Error("UNSUPPORTED_DOMAIN","S01 world has zero life/buildings");if(rules.size()!=3||!rules.contains("aging")||!rules.contains("hunger_consequences")||!rules.contains("thermal_consequences"))throw Error("UNSUPPORTED_RULE","S01 rule set");std::map<std::string,Hash>seen;for(auto&r:receipts){if(r.command_id.empty()||r.command_id.size()>128||!r.committed_revision||r.committed_revision>revision||!seen.emplace(r.command_id,r.payload_hash).second||r.payload_hash!=sha256(canonical_json(r.effects.at("command")))||parse_ref(r.effects.at("before").at("ref"))!=ref()||parse_ref(r.effects.at("after").at("ref"))!=ref()||r.effects.at("elapsed_tick").integer()!=0||r.effects.at("population_change").integer()!=0||r.effects.at("inventory_change").integer()!=0)throw Error("INVALID_RECEIPT","unique command/revision");}if(receipts.size()>1000000)throw Error("SAVE_LIMIT","receipts");(void)canonical_json(provenance);(void)hash_from_hex(provenance.at("surface_sha256").string());if(provenance.at("original_source_read_only").boolean()!=true||provenance.at("core_width").integer()!=terrain.width-2*terrain.guard||provenance.at("core_height").integer()!=terrain.height-2*terrain.guard||provenance.at("soil_theme").integer()<0||provenance.at("soil_theme").integer()>7||((terrain.profile==1||terrain.geometry_revision==1)&&provenance.at("surface_sha256").string()!=hex(terrain.surface_hash())))throw Error("SAVE_PROVENANCE","S01 immutable creation surface");validate_creation_scale(*this);}
World create_candidate(const CreationDraft&d,const DefinitionPackage&defs,const Geography*geo,const std::function<bool()>&cancel,CreationMetrics*metrics){
 if(metrics)*metrics={};if(cancel&&cancel())throw Error("CREATION_CANCELED","before allocation");if(!d.session_generation||!d.draft_generation||!d.candidate_generation)throw Error("STALE_GENERATION","zero");if(d.soil_theme>7)throw Error("INVALID_SOIL_THEME","0..7");if(d.core_width<minimum_core_cells||d.core_width>maximum_core_cells)throw Error("CREATION_DIMENSIONS","core width32..4096");
 int32_t ch=d.core_height;Json::Object source{{"creation_kind",d.kind==CreationKind::Earth?"earth":d.kind==CreationKind::BlankLand?"blank_land":"blank_sea"},{"original_source_read_only",true}};
 if(d.kind==CreationKind::Earth){if(!geo)throw Error("GEO_SOURCE_MISSING","official full source required");auto&r=d.selection;int64_t span=int64_t(r.east_unwrapped_udeg)-r.west_udeg,lat=int64_t(r.north_udeg)-r.south_udeg;if(r.west_udeg< -180000000||r.west_udeg>=180000000||span<=0||span>360000000||lat<=0||r.south_udeg< -90000000||r.north_udeg>90000000)throw Error("EARTH_SELECTION","360 degree / +/-90 degree bounds");int64_t derived=(int64_t(d.core_width)*lat+span-1)/span;if(derived<minimum_core_cells||derived>maximum_core_cells)throw Error("CREATION_DIMENSIONS","derived height32..4096");ch=int32_t(derived);source.emplace("source_sha256",hex(geo->source_hash()));source.emplace("source_version","GSHHG_2.3.7");source.emplace("projection","equirectangular_standard_parallel_0");source.emplace("west_udeg",r.west_udeg);source.emplace("east_unwrapped_udeg",r.east_unwrapped_udeg);source.emplace("south_udeg",r.south_udeg);source.emplace("north_udeg",r.north_udeg);source.emplace("geographic_scale_mode","stylized_uniform_not_1_to_1");source.emplace("game_mm_per_source_microdegree_numerator",int64_t(d.core_width)*terrain_cell_size_mm);source.emplace("game_mm_per_source_microdegree_denominator",span);
 }else if(d.kind!=CreationKind::BlankSea&&d.kind!=CreationKind::BlankLand)throw Error("CREATION_KIND","enum");
 if(ch<minimum_core_cells||ch>maximum_core_cells)throw Error("CREATION_DIMENSIONS","core height32..4096");if(d.budget_bytes<4096||d.budget_bytes>terrain_geometry_budget_bytes)throw Error("CREATION_BUDGET","geometry budget4KiB..128MiB");
 World w;w.id=d.world_id;w.seed=d.seed;w.definition_hash=defs.hash;w.asset_hash=defs.asset_hash;w.name=d.name;w.terrain.storage_budget_bytes=d.budget_bytes;w.terrain.initialize_uniform(d.core_width,ch,{d.kind==CreationKind::BlankLand?TerrainKind::Soil:TerrainKind::CloseOcean,d.kind==CreationKind::BlankLand?d.soil_theme:uint8_t(0),1});if(w.terrain.storage_bytes()>d.budget_bytes)throw Error("CREATION_BUDGET","management rows");if(d.kind==CreationKind::Earth)geo->populate_world(w.terrain,d.selection,d.core_width,ch,d.soil_theme,cancel,metrics);if(cancel&&cancel())throw Error("CREATION_CANCELED","before admission");
 w.rules={{"aging",true},{"hunger_consequences",true},{"thermal_consequences",true}};source.emplace("terrain_profile",2);source.emplace("surface_micro_um",terrain_micro_size_um);source.emplace("micro_divisions",64);source.emplace("soil_theme",int(d.soil_theme));source.emplace("core_width",d.core_width);source.emplace("core_height",ch);source.emplace("terrain_cell_mm",w.terrain.cell_mm);source.emplace("core_physical_width_mm",int64_t(d.core_width)*w.terrain.cell_mm);source.emplace("core_physical_height_mm",int64_t(ch)*w.terrain.cell_mm);source.emplace("domain_physical_width_mm",int64_t(w.terrain.width)*w.terrain.cell_mm);source.emplace("domain_physical_height_mm",int64_t(w.terrain.height)*w.terrain.cell_mm);source.emplace("initial_population",0);source.emplace("initial_awakened_animals",0);source.emplace("initial_buildings",0);source.emplace("surface_sha256",hex(w.terrain.surface_hash()));w.provenance=source;w.validate(defs.hash);if(metrics)metrics->geometry_bytes=w.terrain.storage_bytes();return w;
}
Authority::Authority(World w,uint64_t session):world_(std::move(w)),session_(session),writer_(std::this_thread::get_id()){if(!session_)throw Error("STALE_GENERATION","session");world_.validate(world_.definition_hash);}
void Authority::check_writer()const{if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","owner thread required");}
PreparedCommand Authority::prepare(const Envelope&e,const Command&c)const{check_writer();if(e.world_id!=world_.id||e.session_generation!=session_)throw Error("STALE_GENERATION","world/session");if(e.command_id.empty()||e.command_id.size()>128)throw Error("COMMAND_ID","1..128bytes");auto p=command_payload(c);auto hash=sha256(canonical_json(p));auto i=std::find_if(world_.receipts.begin(),world_.receipts.end(),[&](auto&r){return r.command_id==e.command_id;});if(i!=world_.receipts.end()){if(i->payload_hash!=hash)throw Error("IDEMPOTENCY_CONFLICT",e.command_id);return {e,c,sha256(canonical_json(i->effects)),i->effects};}if(e.expected_revision!=world_.revision)throw Error("STALE_REVISION","reprepare and preview");if(e.input_sequence<=world_.input_sequence||e.input_sequence>uint64_t(INT64_MAX))throw Error("INPUT_SEQUENCE","trusted monotonic input");auto preview=consequence(world_,c);return {e,c,sha256(canonical_json(preview)),std::move(preview)};}
CommandReceipt Authority::commit(const PreparedCommand&p){check_writer();auto hash=sha256(canonical_json(command_payload(p.command)));for(auto&r:world_.receipts)if(r.command_id==p.envelope.command_id){if(r.payload_hash!=hash||p.envelope.world_id!=world_.id||p.envelope.session_generation!=session_)throw Error("IDEMPOTENCY_CONFLICT",r.command_id);return r;}auto again=prepare(p.envelope,p.command);if(again.consequence_hash!=p.consequence_hash||again.preview!=p.preview)throw Error("PREVIEW_CHANGED","reprepare required");World candidate=world_;apply(candidate,p.command);candidate.boundary_ordinal=next(candidate.boundary_ordinal);candidate.input_sequence=p.envelope.input_sequence;candidate.revision=next(candidate.revision);CommandReceipt receipt{p.envelope.command_id,hash,candidate.revision,p.preview};candidate.receipts.push_back(receipt);candidate.validate(candidate.definition_hash);world_=std::move(candidate);return receipt;}
TickTrace Authority::advance_tick(){check_writer();uint64_t tick=next(world_.tick),revision=next(world_.revision);AgeState age=world_.age;
 // No life, pending commands, messages, motion or economy participants exist in S01.
 // Each stage completes before the following barrier; only the last stage publishes authority.
 for(size_t phase=0;phase<phases.size();++phase){switch(phase){
 case 8: // DUE_EXECUTION: actual Age deadline has one owner and advances exactly once.
  if(age.automatic&&--age.remaining_tick==0){age.current=age.current==Age::Light?Age::Darkness:Age::Light;age.remaining_tick=age.current==Age::Light?age.light_duration_tick:age.dark_duration_tick;}break;
 case 10:world_.tick=tick;world_.revision=revision;world_.age=age;break;
 default:break; // Explicit empty-domain barrier, not a claim that future systems are implemented.
 }}return {tick,revision,phases};}
WorldSession::WorldSession():writer_(std::this_thread::get_id()){}
CreationDraft WorldSession::begin(CreationDraft d){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");draft_generation_=next(draft_generation_);candidate_generation_=next(candidate_generation_);d.session_generation=generation_;d.draft_generation=draft_generation_;d.candidate_generation=candidate_generation_;draft_=d;return d;}
void WorldSession::cancel(){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");draft_generation_=next(draft_generation_);candidate_generation_=next(candidate_generation_);draft_.reset();}
bool WorldSession::accepts(const CreationDraft&d)const{return draft_&&d.session_generation==generation_&&d.draft_generation==draft_generation_&&d.candidate_generation==candidate_generation_&&d.world_id==draft_->world_id&&d.kind==draft_->kind&&d.name==draft_->name&&d.core_width==draft_->core_width&&d.core_height==draft_->core_height&&d.soil_theme==draft_->soil_theme&&d.budget_bytes==draft_->budget_bytes&&d.seed==draft_->seed&&d.selection.west_udeg==draft_->selection.west_udeg&&d.selection.east_unwrapped_udeg==draft_->selection.east_unwrapped_udeg&&d.selection.south_udeg==draft_->selection.south_udeg&&d.selection.north_udeg==draft_->selection.north_udeg;}
bool WorldSession::publish(const CreationDraft&d,World c,SaveStore&store,const DefinitionPackage&defs,Checkpoint&result,SaveFault fault){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");if(!accepts(d)||c.id!=d.world_id){result={SaveStatus::Failed,"STALE_GENERATION"};return false;}c.validate(defs.hash);uint64_t g=next(generation_);auto ready=std::make_unique<Authority>(c,g);result=store.save(c,defs,fault);if(result.status!=SaveStatus::Committed)return false;generation_=g;active_=std::move(ready);draft_.reset();return true;}
void WorldSession::load_continue(SaveStore&s,const DefinitionPackage&d){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");auto c=s.continue_world(d);if(!c)throw Error("NO_CONTINUE","no checkpoint");uint64_t g=next(generation_);auto a=std::make_unique<Authority>(std::move(*c),g);generation_=g;draft_.reset();active_=std::move(a);}
void WorldSession::return_to_menu(){if(writer_!=std::this_thread::get_id())throw Error("NOT_SINGLE_WRITER","session");generation_=next(generation_);draft_.reset();active_.reset();}
} // sonn
