#!/usr/bin/env python3
"""Reproduce the original static Sonnheide menu instrument with Python 3.9+.

This geometric interface artwork and its recipe were authored for this project.
No open-content license is assigned. The user's company PNG is a separate,
unmodified asset; it is neither embedded nor regenerated by this tool.
"""
import argparse
import math
from pathlib import Path
import sys


CENTER = 500.0
DESTINATION = Path(__file__).resolve().parents[1] / "assets/source/ui/branding/sonnreich-compass.svg"


def point(radius, angle):
    theta = math.radians(angle)
    return CENTER + radius * math.sin(theta), CENTER - radius * math.cos(theta)


def coordinates(value):
    return "{:.3f},{:.3f}".format(*value)


def radial(start, end, angle, width, opacity):
    a, b = point(start, angle), point(end, angle)
    return ('    <line x1="{:.3f}" y1="{:.3f}" x2="{:.3f}" y2="{:.3f}" '
            'stroke-width="{:.2f}" opacity="{:.3f}"/>').format(a[0], a[1], b[0], b[1], width, opacity)



def circle(radius, width, opacity):
    return ('    <circle cx="500" cy="500" r="{:.3f}" '
            'stroke-width="{:.2f}" opacity="{:.3f}"/>').format(radius, width, opacity)


def group(identifier, geometry):
    return ['  <g id="{}">'.format(identifier)] + geometry + ['  </g>']


def compose():
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" fill="none"',
        '     stroke="#fff6df" stroke-linecap="round" stroke-linejoin="round">',
        '  <metadata>Original Sonnheide interface artwork. Deterministic source: tools/build_menu_compass.py.',
        '    No open-content license has been assigned. Company logo is a separate unmodified user asset.</metadata>',
        '  <!-- Exact topology: clear center, complete inner rings, narrow empty annulus 128-136, fine triple outer edge, subdued dense exterior rays. -->',
        '  <!-- Center radius 105 remains entirely empty. All exterior rays begin at radius 145. -->',
    ]
    parts += group("complete-inner-rings", [circle(116, .50, .66),
                                            circle(121, .35, .48),
                                            circle(127, .65, .74)])

    # Quiet graduations fit inside the inner circles, leaving the narrow gap clear.
    ticks = []
    for i in range(120):
        major, intermediate = i % 10 == 0, i % 5 == 0
        ticks.append(radial(108, 113 if major else 111 if intermediate else 110,
                            i * 3, .70 if major else .45 if intermediate else .30,
                            .66 if major else .49 if intermediate else .35))
    parts += group("120-quiet-inner-graduations", ticks)

    # The outer edge almost touches the inner circles; radii 128-136 stay empty.
    parts += group("complete-triple-outer-edge", [circle(137, .25, .42),
                                                  circle(140, .25, .40),
                                                  circle(144, .50, .48)])

    # Exactly 360 equally spaced rays attach to the outer edge. Six endpoint tiers
    # make the perimeter strongly varied while retaining the precision of a clock.
    rays = []
    for i in range(360):
        if i % 30 == 0:
            end, width, opacity = 490, 1.50, .90
        elif i % 15 == 0:
            end, width, opacity = 420, 1.10, .83
        elif i % 10 == 0:
            end, width, opacity = 330, .85, .75
        elif i % 5 == 0:
            end, width, opacity = 275, .65, .67
        elif i % 3 == 0:
            end, width, opacity = 240, .50, .56
        else:
            end, width, opacity = (240, .35, .50) if i % 2 == 0 else (226, .30, .45)
        rays.append(radial(145, end - 67, i, width, opacity * .60))
    parts += group("360-attached-dense-rays", rays)
    parts.append('</svg>')
    return "\n".join(parts) + "\n"


def svg_bytes():
    """Return the deterministic UTF-8 artwork bytes for manifest/build validation."""
    return compose().encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", "--check", dest="verify", action="store_true", help="verify exact reproducibility without writing")
    args = parser.parse_args()
    artwork = svg_bytes()
    if args.verify:
        if not DESTINATION.is_file() or DESTINATION.read_bytes() != artwork:
            print("Compass SVG differs from its generation recipe", file=sys.stderr)
            return 1
        print("Compass SVG matches its original recipe: 360 subdued attached rays, 120 inner ticks; static, narrow empty annulus 128-136")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_bytes(artwork)
        print("Wrote {}".format(DESTINATION))
    return 0


if __name__ == "__main__":
    sys.exit(main())
